package r45;

/* loaded from: classes9.dex */
public class aw2 extends com.tencent.mm.protobuf.e {
    public aw2() {
        super(com.tencent.mm.protobuf.i.u(1, "finderUsername"), com.tencent.mm.protobuf.i.u(2, "avatar"), com.tencent.mm.protobuf.i.u(3, "nickname"), com.tencent.mm.protobuf.i.u(4, "commodityInStockCount"), com.tencent.mm.protobuf.i.u(5, "appId"), com.tencent.mm.protobuf.i.u(6, com.tencent.kinda.framework.widget.tools.ConstantsKinda.INTENT_LITEAPP_PATH), com.tencent.mm.protobuf.i.u(7, "appUsername"), com.tencent.mm.protobuf.i.u(8, "query"), com.tencent.mm.protobuf.i.u(9, "liteAppId"), com.tencent.mm.protobuf.i.u(10, "liteAppPath"), com.tencent.mm.protobuf.i.u(11, "liteAppQuery"), com.tencent.mm.protobuf.i.u(12, "iconUrl"), com.tencent.mm.protobuf.i.r(13, "reputationInfo", r45.fr5.class), com.tencent.mm.protobuf.i.u(14, "saleWording"), com.tencent.mm.protobuf.i.w(15, "imgList"), com.tencent.mm.protobuf.i.u(16, "lastGMsgID"), com.tencent.mm.protobuf.i.u(17, "profileTypeWording"), com.tencent.mm.protobuf.i.u(18, "saleWordingExtra"), com.tencent.mm.protobuf.i.u(19, "isWxShop"), com.tencent.mm.protobuf.i.u(20, "platformIconUrl"), com.tencent.mm.protobuf.i.u(21, "brandIconUrl"), com.tencent.mm.protobuf.i.u(22, "backgroundUrl"), com.tencent.mm.protobuf.i.u(23, "description"), com.tencent.mm.protobuf.i.u(24, "darkModePlatformIconUrl"), com.tencent.mm.protobuf.i.u(25, "rIconUrl"), com.tencent.mm.protobuf.i.u(26, "rIconUrlDarkMode"), com.tencent.mm.protobuf.i.u(27, "rWords"), com.tencent.mm.protobuf.i.u(28, "topShopIconUrl"), com.tencent.mm.protobuf.i.u(29, "topShopIconUrlDarkMode"), com.tencent.mm.protobuf.i.u(30, "simplifyTopShopIconUrl"), com.tencent.mm.protobuf.i.u(31, "simplifyTopShopIconUrlDarkMode"), com.tencent.mm.protobuf.i.i(32, "topShopIconWidth"), com.tencent.mm.protobuf.i.i(33, "topShopIconHeight"), com.tencent.mm.protobuf.i.i(34, "simplifyTopShopIconWidth"), com.tencent.mm.protobuf.i.i(35, "simplifyTopShopIconHeight"), com.tencent.mm.protobuf.i.i(999, "jumpType"));
        this.__printBytes = true;
    }
}
