package r45;

/* loaded from: classes2.dex */
public class fx2 extends com.tencent.mm.protobuf.e {
    public fx2() {
        super(com.tencent.mm.protobuf.i.i(1, "follow_reddot_prefetch_outter_interval"), com.tencent.mm.protobuf.i.i(2, "friend_reddot_prefetch_outter_interval"), com.tencent.mm.protobuf.i.i(3, "hot_reddot_prefetch_outter_interval"), com.tencent.mm.protobuf.i.i(4, "nearby_reddot_prefetch_outter_interval"), com.tencent.mm.protobuf.i.i(5, "follow_no_reddot_prefetch_outter_interval"), com.tencent.mm.protobuf.i.i(6, "friend_no_reddot_prefetch_outter_interval"), com.tencent.mm.protobuf.i.i(7, "hot_no_reddot_prefetch_outter_interval"), com.tencent.mm.protobuf.i.i(8, "nearby_no_reddot_prefetch_outter_interval"), com.tencent.mm.protobuf.i.i(9, "follow_reddot_prefetch_inner_interval"), com.tencent.mm.protobuf.i.i(10, "friend_reddot_prefetch_inner_interval"), com.tencent.mm.protobuf.i.i(11, "hot_reddot_prefetch_inner_interval"), com.tencent.mm.protobuf.i.i(12, "nearby_reddot_prefetch_inner_interval"), com.tencent.mm.protobuf.i.i(13, "follow_no_reddot_prefetch_inner_interval"), com.tencent.mm.protobuf.i.i(14, "friend_no_reddot_prefetch_inner_interval"), com.tencent.mm.protobuf.i.i(15, "hot_no_reddot_prefetch_inner_interval"), com.tencent.mm.protobuf.i.i(16, "nearby_no_reddot_prefetch_inner_interval"), com.tencent.mm.protobuf.i.c(17, "tab_inner_hot_prefetch_switch"), com.tencent.mm.protobuf.i.i(18, "client_model_prefetch_outter_interval"), com.tencent.mm.protobuf.i.i(19, "client_predict_reddot_outter_interval"), com.tencent.mm.protobuf.i.i(20, "hot_outter_prefetch_model"), com.tencent.mm.protobuf.i.i(21, "new_follow_reddot_prefetch_interval"), com.tencent.mm.protobuf.i.i(22, "new_friend_reddot_prefetch_interval"), com.tencent.mm.protobuf.i.i(23, "new_hot_reddot_prefetch_interval"), com.tencent.mm.protobuf.i.i(24, "new_nearby_reddot_prefetch_interval"), com.tencent.mm.protobuf.i.i(25, "follow_outter_prefetch_valid_time"), com.tencent.mm.protobuf.i.i(26, "friend_outter_prefetch_valid_time"), com.tencent.mm.protobuf.i.i(27, "hot_outter_prefetch_valid_time"), com.tencent.mm.protobuf.i.i(28, "nearby_outter_prefetch_valid_time"), com.tencent.mm.protobuf.i.c(29, "model_prefetch_switch"), com.tencent.mm.protobuf.i.a(30, "ios_model_prefetch_conf"), com.tencent.mm.protobuf.i.i(31, "switch_tab_prefetch_interval"), com.tencent.mm.protobuf.i.i(32, "client_prefetch_valid_time"), com.tencent.mm.protobuf.i.c(33, "frontend_prefetch_switch"), com.tencent.mm.protobuf.i.i(34, "frontend_prefetch_interval_sec"), com.tencent.mm.protobuf.i.i(35, "cache_feed_valid_time"), com.tencent.mm.protobuf.i.c(36, "reddot_frontend_prefetch_switch"));
        this.__printBytes = true;
    }
}
