package r45;

/* loaded from: classes5.dex */
public class kv1 extends com.tencent.mm.protobuf.e {
    public kv1() {
        super(com.tencent.mm.protobuf.i.u(1, "reward_product_id"), com.tencent.mm.protobuf.i.i(2, "business_type"), com.tencent.mm.protobuf.i.u(3, "thumbnail_file_url"), com.tencent.mm.protobuf.i.u(4, "preview_pag_url"), com.tencent.mm.protobuf.i.u(5, "animation_pag_url"), com.tencent.mm.protobuf.i.u(6, "thumbnail_file_md5"), com.tencent.mm.protobuf.i.u(7, "preview_pag_md5"), com.tencent.mm.protobuf.i.u(8, "animation_pag_md5"), com.tencent.mm.protobuf.i.u(9, com.tencent.thumbplayer.tplayer.plugins.report.TPReportKeys.PlayerStep.PLAYER_TRACK_NAME), com.tencent.mm.protobuf.i.g(10, ya.b.PRICE), com.tencent.mm.protobuf.i.i(11, "gift_type"), com.tencent.mm.protobuf.i.i(12, "unlock_intimacy_level"), com.tencent.mm.protobuf.i.i(13, "flag"), com.tencent.mm.protobuf.i.u(14, "landscape_animation_pag_url"), com.tencent.mm.protobuf.i.u(15, "landscape_animation_pag_md5"), com.tencent.mm.protobuf.i.a(16, "custom_info"), com.tencent.mm.protobuf.i.i(17, "unlock_global_reward_level"), com.tencent.mm.protobuf.i.u(18, "tag_color"), com.tencent.mm.protobuf.i.u(19, "tag_text"), com.tencent.mm.protobuf.i.i(20, "unlock_member_level"), com.tencent.mm.protobuf.i.u(21, "interactive_gift_url"), com.tencent.mm.protobuf.i.u(22, "interactive_gift_md5"), com.tencent.mm.protobuf.i.n(23, "duration_time"), com.tencent.mm.protobuf.i.r(24, "batch_give_config_list", r45.qv1.class), com.tencent.mm.protobuf.i.u(25, "description"), com.tencent.mm.protobuf.i.r(26, "jump_info", com.tencent.mm.protocal.protobuf.FinderJumpInfo.class), com.tencent.mm.protobuf.i.c(27, "need_unlock"), com.tencent.mm.protobuf.i.c(28, "disable_combo"), com.tencent.mm.protobuf.i.s(29, "multi_animation_list", r45.yq4.class), com.tencent.mm.protobuf.i.r(30, "switch_skin_info", r45.xi6.class), com.tencent.mm.protobuf.i.r(31, "custom_gift_info", r45.na0.class), com.tencent.mm.protobuf.i.i(32, "free_gift_seq"), com.tencent.mm.protobuf.i.r(33, "foreground_info", r45.l43.class), com.tencent.mm.protobuf.i.c(34, "use_rfx_pag"), com.tencent.mm.protobuf.i.r(37, "audience_ai_custom_gift_info", r45.mb.class), com.tencent.mm.protobuf.i.r(38, "designer_info", r45.wd0.class));
        this.__printBytes = true;
    }
}
