package r45;

/* loaded from: classes5.dex */
public class rg0 extends com.tencent.mm.protobuf.e {
    public rg0() {
        super(com.tencent.mm.protobuf.i.n(1, "product_id"), com.tencent.mm.protobuf.i.u(2, com.tencent.mm.plugin.mmsight.segment.FFmpegMetadataRetriever.METADATA_KEY_TITLE), com.tencent.mm.protobuf.i.w(3, "img_urls"), com.tencent.mm.protobuf.i.i(4, "stock"), com.tencent.mm.protobuf.i.i(5, "market_price"), com.tencent.mm.protobuf.i.i(6, "selling_price"), com.tencent.mm.protobuf.i.i(7, "status"), com.tencent.mm.protobuf.i.u(8, "platform_name"), com.tencent.mm.protobuf.i.r(9, "half_page", r45.pg0.class), com.tencent.mm.protobuf.i.r(10, "full_page", r45.pg0.class), com.tencent.mm.protobuf.i.i(11, "platform_id"), com.tencent.mm.protobuf.i.u(12, com.tencent.kinda.framework.widget.tools.ConstantsKinda.INTENT_LITEAPP_EXTRA_DATA), com.tencent.mm.protobuf.i.u(13, "button_wording"), com.tencent.mm.protobuf.i.u(14, "request_id"), com.tencent.mm.protobuf.i.i(15, "discount_price"), com.tencent.mm.protobuf.i.s(16, "associated_coupons", r45.jg0.class), com.tencent.mm.protobuf.i.i(17, "product_type"), com.tencent.mm.protobuf.i.u(18, "out_product_id"), com.tencent.mm.protobuf.i.u(19, "product_path_cookie"), com.tencent.mm.protobuf.i.c(20, "is_virtual_product"), com.tencent.mm.protobuf.i.s(21, "show_box_items", r45.tg0.class), com.tencent.mm.protobuf.i.c(22, "has_limit_discount"), com.tencent.mm.protobuf.i.i(23, "sales"), com.tencent.mm.protobuf.i.u(24, "selling_price_wording"), com.tencent.mm.protobuf.i.i(25, "is_market_price_show"), com.tencent.mm.protobuf.i.r(26, "virtual_price_info", r45.wg0.class), com.tencent.mm.protobuf.i.u(27, "appid"), com.tencent.mm.protobuf.i.w(28, "icon_urls"), com.tencent.mm.protobuf.i.i(29, "product_button_status"), com.tencent.mm.protobuf.i.i(30, "is_price_begin_show"), com.tencent.mm.protobuf.i.i(31, "need_pre_open_disclaimer"), com.tencent.mm.protobuf.i.i(32, "product_business_type"), com.tencent.mm.protobuf.i.u(33, "price_suffix_description"), com.tencent.mm.protobuf.i.s(34, "product_icon_tags", r45.vy3.class), com.tencent.mm.protobuf.i.i(35, "discount_rate"), com.tencent.mm.protobuf.i.u(36, "product_encrypt_key"), com.tencent.mm.protobuf.i.c(37, "is_wx_shop"), com.tencent.mm.protobuf.i.u(38, "platform_icon_url"), com.tencent.mm.protobuf.i.u(39, "brand_icon_url"), com.tencent.mm.protobuf.i.i(200, "need_cover_grey_matte"));
        this.__printBytes = true;
    }
}
