package r45;

/* loaded from: classes5.dex */
public class ta4 extends com.tencent.mm.protobuf.e {
    public ta4() {
        super(com.tencent.mm.protobuf.i.i(1, "notice_type"), com.tencent.mm.protobuf.i.a(2, "uxinfo"), com.tencent.mm.protobuf.i.u(3, "jumperSessionBuffer"), com.tencent.mm.protobuf.i.u(4, "finderForwardSource"), com.tencent.mm.protobuf.i.i(5, "session_type"), com.tencent.mm.protobuf.i.u(6, "share_username"), com.tencent.mm.protobuf.i.i(7, "is_enterprise"), com.tencent.mm.protobuf.i.c(8, "isFromQrcode"), com.tencent.mm.protobuf.i.c(9, "isFromRecomEnter"), com.tencent.mm.protobuf.i.u(10, "enterPkUserName"), com.tencent.mm.protobuf.i.i(11, "livePosition"), com.tencent.mm.protobuf.i.a(12, "notifyGift"), com.tencent.mm.protobuf.i.i(13, "notification_msg_type"), com.tencent.mm.protobuf.i.r(14, "chnl_extra", r45.k30.class), com.tencent.mm.protobuf.i.i(15, "vipLivePrice"), com.tencent.mm.protobuf.i.u(16, "joinLiveColumnId"), com.tencent.mm.protobuf.i.a(17, "replayGiftMsg"), com.tencent.mm.protobuf.i.n(18, "fromFeedLiveId"), com.tencent.mm.protobuf.i.r(19, "manue_trigger_join_live", r45.li4.class), com.tencent.mm.protobuf.i.c(20, "transferComments"), com.tencent.mm.protobuf.i.s(21, "livestep", r45.qa4.class), com.tencent.mm.protobuf.i.c(22, "searchH5feedFocusChangeNotify"), com.tencent.mm.protobuf.i.u(23, "liteAppId"), com.tencent.mm.protobuf.i.s(24, "live_mode_control_info", r45.p12.class), com.tencent.mm.protobuf.i.r(25, "anchor_quest_entrance", r45.ug1.class), com.tencent.mm.protobuf.i.c(26, "disableHistory"), com.tencent.mm.protobuf.i.i(27, "use_simple_create_live_mode"), com.tencent.mm.protobuf.i.r(28, "game_play_together_entrance_info", r45.zq1.class), com.tencent.mm.protobuf.i.r(29, "page_mode_poi_topic_control_info", r45.a45.class), com.tencent.mm.protobuf.i.c(30, "can_use_create_live_page_simple_mode"), com.tencent.mm.protobuf.i.a(31, "out_room_realname_like_info"), com.tencent.mm.protobuf.i.s(32, "backupLiveConfigList", r45.sp1.class), com.tencent.mm.protobuf.i.u(33, "columnVMKey"), com.tencent.mm.protobuf.i.c(34, "disable_relative_live_sidebar"), com.tencent.mm.protobuf.i.i(35, "relativeListRequestType"), com.tencent.mm.protobuf.i.a(36, "create_live_prepare_buffer"), com.tencent.mm.protobuf.i.a(37, "open_live_h5_buffer"));
        this.__printBytes = true;
    }
}
