import os
path = r"app\src\main\java\com\muchen\weiplus\features\GameCheatFeature.kt"
os.makedirs(os.path.dirname(path), exist_ok=True)

L = []
def a(s): L.append(s)

a("package com.muchen.weiplus.features")
a("")
a("import android.app.AlertDialog")
a("import android.os.Handler")
a("import android.os.Looper")
a("import android.util.Log")
a("import android.view.View")
a("import io.github.libxposed.api.XposedModule")
a("")
a("class GameCheatFeature : BaseFeature() {")
a("")
a("    companion object { private const val TAG = \"GameCheat\" }")
a("    override val key = \"game_cheat\"")
a("    override val name = \"Game Cheat\"")
a("")
a("    private val dq = \"\\\"\"")
a("    private lateinit var module: XposedModule")
a("    private var classLoader: ClassLoader? = null")
a("    private val mainHandler = Handler(Looper.getMainLooper())")
a("    private var blockedChain: Any? = null")
a("    private var blockedContent: String? = null")
a("    private var blockedGameType = 0")
a("    private var blockedArgsIdx = 0")
a("    private var currentDialog: AlertDialog? = null")
a("    private val gameEmojiFiles = setOf(\"jsb.png\", \"dice.png\", \"jsb\", \"dice\")")
a("")
a("    override fun onEnable(module: XposedModule, classLoader: ClassLoader) {")
a("        this.module = module")
a("        this.classLoader = classLoader")
a("        hookEmojiInfoIntercept(classLoader)")
a("        hookWcdbIntercept(classLoader)")
a("        hookAdapterViewClick(classLoader)")
a("        hookAllGameClasses(classLoader)")
a("        module.log(Log.INFO, TAG, \"OK\")")
a("    }")
a("")
a("    // ========= Strategy 1: EmojiInfo intercept (primary) =========")
a("")
a("    private fun hookEmojiInfoIntercept(cl: ClassLoader) {")
a("        val clsNames = listOf(")
a("            \"com.tencent.mm.storage.emotion.EmojiInfo\",")
a("            \"com.tencent.mm.plugin.emoji.model.EmojiInfo\",")
a("        )")
a("        for (cn in clsNames) {")
a("            try {")
a("                val cls = cl.loadClass(cn)")
a("                for (m in cls.declaredMethods) {")
a("                    val mn = m.name.lowercase()")
a("                    val isTarget = mn in listOf(\"setcontent\", \"getcontent\", \"getxmldata\",")
a("                        \"setxmldata\", \"toxml\", \"getgamecontent\", \"setgamecontent\",")
a("                        \"getgameresult\", \"setgameresult\")")
a("                    val hasStringParam = m.parameterTypes.any { it == String::class.java }")
a("                    val hasStringReturn = m.returnType == String::class.java")
a("                    if (isTarget || (hasStringParam && m.parameterTypes.size <= 2) || hasStringReturn) {")
a("                        module.hook(m).intercept { chain ->")
a("                            if (!FeatureConfig.gameCheat) return@intercept chain.proceed()")
a("                            val result = chain.proceed()")
a("                            val resStr = result as? String ?: \"\"")
a("                            if (resStr.isNotEmpty() && isGameEmoji(resStr)) {")
a("                                module.log(Log.INFO, TAG, \"EI.${m.name} GAME: ${resStr.take(120)}\")")
a("                                blockedChain = chain; blockedContent = resStr")
a("                                blockedGameType = if (resStr.lowercase().contains(\"dice\") || resStr.lowercase().contains(\"gameext\")) 2 else 1")
a("                                mainHandler.post { showPicker() }")
a("                                return@intercept resStr")
a("                            }")
a("                            for (i in chain.args.indices) {")
a("                                val ar = chain.args[i]")
a("                                if (ar is String && isGameEmoji(ar)) {")
a("                                    module.log(Log.INFO, TAG, \"EI.${m.name} ARG GAME: ${ar.take(120)}\")")
a("                                    blockedChain = chain; blockedContent = ar; blockedArgsIdx = i")
a("                                    blockedGameType = if (ar.lowercase().contains(\"dice\") || ar.lowercase().contains(\"gameext\")) 2 else 1")
a("                                    mainHandler.post { showPicker() }")
a("                                    return@intercept null")
a("                                }")
a("                            }")
a("                            result")
a("                        }")
a("                        module.log(Log.INFO, TAG, \"EI.${m.name} hooked\")")
a("                    }")
a("                }")
a("            } catch (e: Throwable) { module.log(Log.DEBUG, TAG, \"EI skip $cn: ${e.message}\") }")
a("        }")
a("    }")
a("")
a("    // ========= Strategy 2: WCDB intercept (fallback 1) =========")
a("")
a("    private fun hookWcdbIntercept(cl: ClassLoader) {")
a("        try {")
a("            val wcdb = cl.loadClass(\"com.tencent.wcdb.database.SQLiteDatabase\")")
a("            for (m in wcdb.declaredMethods) {")
a("                if ((m.name == \"insert\" || m.name == \"replace\") && m.parameterTypes.size >= 3) {")
a("                    module.hook(m).intercept { chain ->")
a("                        if (!FeatureConfig.gameCheat) return@intercept chain.proceed()")
a("                        try {")
a("                            val table = chain.args.getOrNull(0)?.toString() ?: \"\"")
a("                            if (!table.contains(\"message\", ignoreCase = true)) return@intercept chain.proceed()")
a("                            for (arg in chain.args) {")
a("                                if (arg?.javaClass?.name?.contains(\"ContentValues\") == true) {")
a("                                    val getStr = arg.javaClass.getMethod(\"getAsString\", String::class.java)")
a("                                    val content = getStr.invoke(arg, \"content\") as? String ?: continue")
a("                                    if (isGameEmoji(content)) {")
a("                                        val getAsInt = arg.javaClass.getMethod(\"getAsInteger\", String::class.java)")
a("                                        val type = try { (getAsInt.invoke(arg, \"type\") as? Number)?.toInt() } catch (_: Throwable) { -1 }")
a("                                        module.log(Log.INFO, TAG, \"WCDB GAME type=$type content=${content.take(120)}\")")
a("                                        blockedArgsIdx = 1; setupBlock(chain, content)")
a("                                        return@intercept null")
a("                                    }")
a("                                    val getAsInt = arg.javaClass.getMethod(\"getAsInteger\", String::class.java)")
a("                                    val type = try { (getAsInt.invoke(arg, \"type\") as? Number)?.toInt() } catch (_: Throwable) { null }")
a("                                    if (type != null && type != 0 && type != 1) {")
a("                                        module.log(Log.INFO, TAG, \"MSG t=$type: cnt=${getStr.invoke(arg, \"content\")?.toString()?.take(80)}\")")
a("                                    }")
a("                                }")
a("                            }")
a("                        } catch (_: Throwable) {}")
a("                        chain.proceed()")
a("                    }")
a("                    module.log(Log.INFO, TAG, \"WCDB hooked\")")
a("                    return")
a("                }")
a("            }")
a("        } catch (e: Throwable) { module.log(Log.ERROR, TAG, \"WCDB: ${e.message}\") }")
a("    }")
a("")
a("    // ========= Strategy 3: AdapterView click (fallback 2) =========")
a("")
a("    private fun hookAdapterViewClick(cl: ClassLoader) {")
a("        try {")
a("            val av = cl.loadClass(\"android.widget.AdapterView\")")
a("            val m = av.getDeclaredMethod(\"performItemClick\", View::class.java, Integer.TYPE, java.lang.Long.TYPE)")
a("            module.hook(m).intercept { chain ->")
a("                if (!FeatureConfig.gameCheat) return@intercept chain.proceed()")
a("                val ao = chain.thisObject")
a("                val cn = ao.javaClass.name")
a("                val lc = cn.lowercase()")
a("                if (lc.contains(\"emoji\") || lc.contains(\"sticker\") || lc.contains(\"smiley\")) {")
a("                    val pos = chain.args[1] as Int")
a("                    try {")
a("                        val ad = ao.javaClass.getMethod(\"getAdapter\").invoke(ao)")
a("                        val item = ad?.javaClass?.getMethod(\"getItem\", Integer.TYPE)?.invoke(ad, pos)")
a("                        val its = item?.toString() ?: \"\"")
a("                        module.log(Log.INFO, TAG, \"ADAPTER $cn pos=$pos item=${its.take(200)}\")")
a("                        if (isGameEmoji(its) || gameEmojiFiles.any { its.lowercase().contains(it) }) {")
a("                            module.log(Log.INFO, TAG, \"ADAPTER GAME: ${its.take(200)}\")")
a("                            blockedChain = chain; blockedContent = its; blockedArgsIdx = 1")
a("                            blockedGameType = if (its.lowercase().contains(\"dice\")) 2 else 1")
a("                            mainHandler.post { showPicker() }")
a("                            return@intercept null")
a("                        }")
a("                    } catch (e: Throwable) { module.log(Log.DEBUG, TAG, \"ADAPTER err: ${e.message}\") }")
a("                }")
a("                chain.proceed()")
a("            }")
a("            module.log(Log.INFO, TAG, \"AdapterView hooked\")")
a("        } catch (e: Throwable) { module.log(Log.ERROR, TAG, \"AdapterView: ${e.message}\") }")
a("    }")
a("")
a("    // ========= Strategy 4: Diagnostic hooks (from v8) =========")
a("")
a("    private fun hookAllGameClasses(cl: ClassLoader) {")
a("        val targets = listOf(")
a("            \"com.tencent.mm.plugin.game.luggage\",")
a("            \"com.tencent.mm.plugin.game.download.GameResourceDownloadProvider\",")
a("            \"com.tencent.mm.plugin.game.ui.GameMessageUI\",")
a("            \"com.tencent.mm.plugin.game.luggage.c\",")
a("            \"com.tencent.mm.plugin.game.luggage.d\",")
a("            \"com.tencent.mm.plugin.game.luggage.e\",")
a("            \"com.tencent.mm.plugin.emoji.b.d\",")
a("            \"com.tencent.mm.storage.emotion.EmojiInfo\",")
a("            \"com.tencent.mm.plugin.emoji.model.EmojiInfo\",")
a("            \"com.tencent.mm.message.AppMessage\",")
a("        )")
a("        for (cn in targets) {")
a("            try {")
a("                val cls = cl.loadClass(cn)")
a("                for (m in cls.declaredMethods) {")
a("                    if (m.parameterTypes.size in 0..6) {")
a("                        module.hook(m).intercept { chain ->")
a("                            if (!FeatureConfig.gameCheat) return@intercept chain.proceed()")
a("                            val sb = StringBuilder()")
a("                            for (i in chain.args.indices) {")
a("                                val a = chain.args[i]")
a("                                val s = if (a is String) a.take(80) else a?.toString()?.take(40) ?: \"null\"")
a("                                if (s != \"null\" && s.isNotEmpty()) sb.append(\"a$i=$s | \")")
a("                            }")
a("                            val result = chain.proceed()")
a("                            if (result is String && result.length > 5) sb.append(\"ret=${result.take(120)}\")")
a("                            if (sb.isNotEmpty()) module.log(Log.INFO, TAG, \"$cn.${m.name}: $sb\")")
a("                            result")
a("                        }")
a("                    }")
a("                }")
a("                module.log(Log.INFO, TAG, \"$cn hooked\")")
a("            } catch (_: Throwable) {}")
a("        }")
a("    }")
a("")
a("    // ========= Core logic =========")
a("")
a("    private fun isGameEmoji(c: String): Boolean {")
a("        if (c.length < 30) return false")
a("        val lc = c.lowercase()")
a("        return (lc.contains(\"<emoji\") || lc.contains(\"<gameext\") || lc.contains(\"gamecontent\")) &&")
a("               (lc.contains(\"<msg\") || lc.contains(\"fromusername\") || lc.contains(\"tousername\") || lc.contains(\"<emotion\"))")
a("    }")
a("")
a("    private fun setupBlock(chain: Any, content: String) {")
a("        blockedChain = chain; blockedContent = content")
a("        blockedGameType = if (content.lowercase().contains(\"dice\") || content.lowercase().contains(\"gameext\")) 2 else 1")
a("        mainHandler.post { showPicker() }")
a("    }")
a("")

RPS_ITEMS = '            arrayOf("\u270a \u77f3\u5934", "\u270c\ufe0f \u526a\u5200", "\U0001f590 \u5e03")'

a("    private fun showPicker() {")
a("        val ctx = tryGetActivity()")
a("        if (ctx == null) {")
a("            module.log(Log.WARN, TAG, \"no activity, bypass\")")
a("            proceedBlocked()")
a("            return")
a("        }")
a("        val gt = blockedGameType")
a("        val title = if (gt == 2) \"\u9009\u62e9\u9ab0\u5b50\u70b9\u6570\" else \"\u9009\u62e9\u731c\u62f3\u7ed3\u679c\"")
a("        val items = if (gt == 2)")
a("            arrayOf(\"\u2680 1\", \"\u2681 2\", \"\u2682 3\", \"\u2683 4\", \"\u2684 5\", \"\u2685 6\")")
a("        else")
a(RPS_ITEMS)
a("")
a("        currentDialog = AlertDialog.Builder(ctx)")
a("            .setTitle(title)")
a("            .setItems(items) { _, which ->")
a("                val chosen = if (gt == 1)")
a("                    when (which) { 0 -> 2; 1 -> 1; 2 -> 0; else -> 0 }")
a("                else which + 1")
a("                module.log(Log.INFO, TAG, \"Chose: gt=$gt idx=$which val=$chosen\")")
a("                replaceContent(chosen, gt)")
a("            }")
a("            .setOnCancelListener { proceedBlocked() }")
a("            .create()")
a("        try {")
a("            currentDialog?.window?.setType(android.view.WindowManager.LayoutParams.TYPE_APPLICATION)")
a("        } catch (_: Throwable) {}")
a("        currentDialog?.show()")
a("        module.log(Log.INFO, TAG, \"Dialog shown: gt=$gt\")")
a("    }")
a("")
a("    private fun replaceContent(chosen: Int, gameType: Int) {")
a("        try {")
a("            val chain = blockedChain ?: run { proceedBlocked(); return }")
a("            val c = blockedContent ?: run { proceedBlocked(); return }")
a("")
a("            val newContent = if (gameType == 2) {")
a("                c.replace(Regex(\"(content|type)=\" + dq + \"\\\\d+\" + dq, RegexOption.IGNORE_CASE),")
a("                    \"content=\" + dq + chosen + dq)")
a("            } else {")
a("                c.replace(Regex(\"type=\" + dq + \"\\\\d+\" + dq, RegexOption.IGNORE_CASE),")
a("                    \"type=\" + dq + chosen + dq)")
a("            }")
a("")
a("            module.log(Log.INFO, TAG, \"Cheat: gt=$gameType v=$chosen old=${c.take(80)} new=${newContent.take(80)}\")")
a("")
a("            try {")
a("                val af = chain.javaClass.getDeclaredField(\"args\"); af.isAccessible = true")
a("                val args = af.get(chain) as Array<Any?>")
a("                var idx = blockedArgsIdx")
a("                if (idx >= args.size) idx = 0")
a("                if (args.isNotEmpty() && args[0] is String && isGameEmoji(args[0] as String)) idx = 0")
a("                args[idx] = newContent")
a("            } catch (_: Throwable) {}")
a("            chain.javaClass.getMethod(\"proceed\").invoke(chain)")
a("        } catch (e: Throwable) {")
a("            module.log(Log.ERROR, TAG, \"replace err: ${e.message}\")")
a("            proceedBlocked()")
a("        } finally {")
a("            blockedChain = null; blockedContent = null")
a("            currentDialog?.dismiss(); currentDialog = null")
a("        }")
a("    }")
a("")
a("    private fun proceedBlocked() {")
a("        try { blockedChain?.javaClass?.getMethod(\"proceed\")?.invoke(blockedChain) } catch (_: Throwable) {}")
a("        blockedChain = null; blockedContent = null")
a("        currentDialog?.dismiss(); currentDialog = null")
a("    }")
a("")
a("    private fun tryGetActivity(): android.app.Activity? {")
a("        return try {")
a("            val c = Class.forName(\"android.app.ActivityThread\")")
a("            val am = c.getDeclaredMethod(\"currentActivityThread\").invoke(null)")
a("            val f = c.getDeclaredField(\"mActivities\"); f.isAccessible = true")
a("            @Suppress(\"UNCHECKED_CAST\")")
a("            val acts = f.get(am) as? Map<Any, Any>")
a("            if (acts != null) for (rec in acts.values) {")
a("                try {")
a("                    val af = rec.javaClass.getDeclaredField(\"activity\"); af.isAccessible = true")
a("                    val a = af.get(rec)")
a("                    if (a is android.app.Activity && !a.isFinishing) return a")
a("                } catch (_: Throwable) {}")
a("            }")
a("            null")
a("        } catch (_: Throwable) { null }")
a("    }")
a("}")

with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(L))
print("OK")
