import os
path = r"app\src\main\java\com\muchen\weiplus\features\GameCheatFeature.kt"
os.makedirs(os.path.dirname(path), exist_ok=True)

L = []
def a(s): L.append(s)

a("package com.muchen.weiplus.features")
a("")
a("import android.app.AlertDialog")
a("import android.os.Handler")
a("import android.os.Looper")
a("import android.util.Log")
a("import android.view.View")
a("import io.github.libxposed.api.XposedModule")
a("")
a("class GameCheatFeature : BaseFeature() {")
a("")
a("    companion object { private const val TAG = \"GameCheat\" }")
a("    override val key = \"game_cheat\"")
a("    override val name = \"Game Cheat\"")
a("")
a("    private val dq = \"\\\"\"")
a("    private lateinit var module: XposedModule")
a("    private var classLoader: ClassLoader? = null")
a("    private val mainHandler = Handler(Looper.getMainLooper())")
a("    private var blockedChain: Any? = null")
a("    private var blockedContent: String? = null")
a("    private var blockedGameType = 0")
a("    private var blockedArgsIdx = 0")
a("    private var currentDialog: AlertDialog? = null")
a("    private var lastClickTime = 0L")
a("")
a("    override fun onEnable(module: XposedModule, classLoader: ClassLoader) {")
a("        this.module = module")
a("        this.classLoader = classLoader")
a("        hookViewClick()")
a("        hookAllGameClasses(classLoader)")
a("        module.log(Log.INFO, TAG, \"OK\")")
a("    }")
a("")
a("    // ========= Strategy: Hook ALL View clicks in emoji context =========")
a("")
a("    private fun hookViewClick() {")
a("        try {")
a("            val m = View::class.java.getDeclaredMethod(\"performClick\")")
a("            module.hook(m).intercept { chain ->")
a("                if (!FeatureConfig.gameCheat) return@intercept chain.proceed()")
a("                val v = chain.thisObject as? View ?: return@intercept chain.proceed()")
a("                val cn = v.javaClass.name")
a("                // Only check views that could be emoji items")
a("                val lc = cn.lowercase()")
a("                val inEmoji = lc.contains(\"emoji\") || lc.contains(\"sticker\") || lc.contains(\"smiley\")")
a("                val ctxStr = v.context?.javaClass?.name?.lowercase() ?: \"\"")
a("                val inEmojiCtx = ctxStr.contains(\"emoji\") || ctxStr.contains(\"chatting\") || ctxStr.contains(\"launcher\")")
a("                if (!inEmoji && !inEmojiCtx) return@intercept chain.proceed()")
a("")
a("                // Try to get emoji info from the view")
a("                val tag = try { v.tag } catch (_: Throwable) { null }")
a("                val tagStr = tag?.toString() ?: \"\"")
a("                // Also try getting contentDescription or text")
a("                val cd = try { v.contentDescription?.toString() } catch (_: Throwable) { null } ?: \"\"")
a("")
a("                val combined = \"$tagStr $cd\"")
a("                val now = System.currentTimeMillis()")
a("")
a("                // Log all emoji-related clicks for debugging")
a("                if (combined.isNotEmpty()) {")
a("                    module.log(Log.INFO, TAG, \"CLICK $cn tag=${combined.take(120)}\")")
a("                } else {")
a("                    val parent = try { (v.parent as? View)?.javaClass?.name } catch (_: Throwable) { \"?\" }")
a("                    module.log(Log.INFO, TAG, \"CLICK $cn parent=$parent\")")
a("                }")
a("")
a("                // Check if this is a game emoji click")
a("                val isGame = combined.lowercase().let { s ->")
a("                    s.contains(\"jsb\") || s.contains(\"dice\") || s.contains(\"game\") ||")
a("                    s.contains(\"猜拳\") || s.contains(\"骰子\")")
a("                }")
a("                if (isGame) {")
a("                    module.log(Log.INFO, TAG, \"CLICK GAME DETECTED: $cn tag=${combined.take(200)}\")")
a("                    // Block the click, show dialog")
a("                    blockedChain = chain")
a("                    blockedContent = combined")
a("                    blockedGameType = if (combined.lowercase().contains(\"dice\") || combined.lowercase().contains(\"骰子\")) 2 else 1")
a("                    mainHandler.post { showPicker() }")
a("                    return@intercept null")
a("                }")
a("")
a("                chain.proceed()")
a("            }")
a("            module.log(Log.INFO, TAG, \"View.click hooked\")")
a("        } catch (e: Throwable) { module.log(Log.ERROR, TAG, \"View.click: ${e.message}\") }")
a("    }")
a("")
a("    // ========= Diagnostic hooks =========")
a("")
a("    private fun hookAllGameClasses(cl: ClassLoader) {")
a("        val targets = listOf(")
a("            \"com.tencent.mm.storage.emotion.EmojiInfo\",")
a("            \"com.tencent.mm.plugin.emoji.model.EmojiInfo\",")
a("            \"com.tencent.mm.plugin.emoji.b.d\",")
a("            \"com.tencent.mm.message.AppMessage\",")
a("        )")
a("        for (cn in targets) {")
a("            try {")
a("                val cls = cl.loadClass(cn)")
a("                for (m in cls.declaredMethods) {")
a("                    if (m.parameterTypes.size in 0..6) {")
a("                        module.hook(m).intercept { chain ->")
a("                            if (!FeatureConfig.gameCheat) return@intercept chain.proceed()")
a("                            val sb = StringBuilder()")
a("                            for (i in chain.args.indices) {")
a("                                val a = chain.args[i]")
a("                                val s = if (a is String) a.take(80) else a?.toString()?.take(40) ?: \"null\"")
a("                                if (s != \"null\" && s.isNotEmpty()) sb.append(\"a$i=$s | \")")
a("                            }")
a("                            val result = chain.proceed()")
a("                            if (result is String && result.length > 5) sb.append(\"ret=${result.take(120)}\")")
a("                            if (sb.isNotEmpty()) module.log(Log.INFO, TAG, \"$cn.${m.name}: $sb\")")
a("                            result")
a("                        }")
a("                    }")
a("                }")
a("                module.log(Log.INFO, TAG, \"$cn hooked\")")
a("            } catch (_: Throwable) {}")
a("        }")
a("    }")
a("")
a("    // ========= Core logic =========")
a("")
a("    private fun isGameEmoji(c: String): Boolean {")
a("        if (c.length < 30) return false")
a("        val lc = c.lowercase()")
a("        return (lc.contains(\"<emoji\") || lc.contains(\"<gameext\") || lc.contains(\"gamecontent\")) &&")
a("               (lc.contains(\"<msg\") || lc.contains(\"fromusername\") || lc.contains(\"tousername\") || lc.contains(\"<emotion\"))")
a("    }")
a("")

RPS_ITEMS = '            arrayOf("\u270a \u77f3\u5934", "\u270c\ufe0f \u526a\u5200", "\U0001f590 \u5e03")'

a("    private fun showPicker() {")
a("        val ctx = tryGetActivity()")
a("        if (ctx == null) {")
a("            module.log(Log.WARN, TAG, \"no activity, bypass\")")
a("            proceedBlocked()")
a("            return")
a("        }")
a("        val gt = blockedGameType")
a("        val title = if (gt == 2) \"\u9009\u62e9\u9ab0\u5b50\u70b9\u6570\" else \"\u9009\u62e9\u731c\u62f3\u7ed3\u679c\"")
a("        val items = if (gt == 2)")
a("            arrayOf(\"\u2680 1\", \"\u2681 2\", \"\u2682 3\", \"\u2683 4\", \"\u2684 5\", \"\u2685 6\")")
a("        else")
a(RPS_ITEMS)
a("")
a("        currentDialog = AlertDialog.Builder(ctx)")
a("            .setTitle(title)")
a("            .setItems(items) { _, which ->")
a("                val chosen = if (gt == 1)")
a("                    when (which) { 0 -> 2; 1 -> 1; 2 -> 0; else -> 0 }")
a("                else which + 1")
a("                module.log(Log.INFO, TAG, \"Chose: gt=$gt idx=$which val=$chosen\")")
a("                replaceContent(chosen, gt)")
a("            }")
a("            .setOnCancelListener { proceedBlocked() }")
a("            .create()")
a("        try {")
a("            currentDialog?.window?.setType(android.view.WindowManager.LayoutParams.TYPE_APPLICATION)")
a("        } catch (_: Throwable) {}")
a("        currentDialog?.show()")
a("        module.log(Log.INFO, TAG, \"Dialog shown: gt=$gt\")")
a("    }")
a("")
a("    private fun replaceContent(chosen: Int, gameType: Int) {")
a("        try {")
a("            val chain = blockedChain ?: run { proceedBlocked(); return }")
a("            // First let the original click proceed to trigger WeChat's send")
a("            proceedBlocked()")
a("            // Then hook the send to modify content before it goes out")
a("            // For now just proceed and accept that we intercepted the click")
a("            module.log(Log.INFO, TAG, \"Cheat: gt=$gameType v=$chosen\")")
a("        } catch (e: Throwable) {")
a("            module.log(Log.ERROR, TAG, \"replace err: ${e.message}\")")
a("            proceedBlocked()")
a("        }")
a("    }")
a("")
a("    private fun proceedBlocked() {")
a("        try { blockedChain?.javaClass?.getMethod(\"proceed\")?.invoke(blockedChain) } catch (_: Throwable) {}")
a("        blockedChain = null; blockedContent = null")
a("        currentDialog?.dismiss(); currentDialog = null")
a("    }")
a("")
a("    private fun tryGetActivity(): android.app.Activity? {")
a("        return try {")
a("            val c = Class.forName(\"android.app.ActivityThread\")")
a("            val am = c.getDeclaredMethod(\"currentActivityThread\").invoke(null)")
a("            val f = c.getDeclaredField(\"mActivities\"); f.isAccessible = true")
a("            @Suppress(\"UNCHECKED_CAST\")")
a("            val acts = f.get(am) as? Map<Any, Any>")
a("            if (acts != null) for (rec in acts.values) {")
a("                try {")
a("                    val af = rec.javaClass.getDeclaredField(\"activity\"); af.isAccessible = true")
a("                    val a = af.get(rec)")
a("                    if (a is android.app.Activity && !a.isFinishing) return a")
a("                } catch (_: Throwable) {}")
a("            }")
a("            null")
a("        } catch (_: Throwable) { null }")
a("    }")
a("}")

with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(L))
print("OK")
