import os
path = r"app\src\main\java\com\muchen\weiplus\features\GameCheatFeature.kt"
os.makedirs(os.path.dirname(path), exist_ok=True)
lines = []
lines.append("package com.muchen.weiplus.features")
lines.append("")
lines.append("import android.app.AlertDialog")
lines.append("import android.os.Handler")
lines.append("import android.os.Looper")
lines.append("import android.util.Log")
lines.append("import android.view.View")
lines.append("import io.github.libxposed.api.XposedModule")
lines.append("")
lines.append("class GameCheatFeature : BaseFeature() {")
lines.append("")
lines.append("    companion object { private const val TAG = \"GameCheat\" }")
lines.append("")
lines.append("    override val key = \"game_cheat\"")
lines.append("    override val name = \"Game Cheat\"")
lines.append("")
lines.append("    private lateinit var module: XposedModule")
lines.append("    private var classLoader: ClassLoader? = null")
lines.append("    private val mainHandler = Handler(Looper.getMainLooper())")
lines.append("    private var blockedChain: Any? = null")
lines.append("    private var blockedContent: String? = null")
lines.append("")
lines.append("    override fun onEnable(module: XposedModule, classLoader: ClassLoader) {")
lines.append("        this.module = module")
lines.append("        this.classLoader = classLoader")
lines.append("        hookClassLoader(classLoader)")
lines.append("        tryHookKnownTargets(classLoader)")
lines.append("        hookViewPerformClick()")
lines.append("        hookAdapterViewClick()")
lines.append("        module.log(Log.INFO, TAG, \"OK\")")
lines.append("    }")
lines.append("")
lines.append("    private fun hookClassLoader(cl: ClassLoader) {")
lines.append("        try {")
lines.append("            val m = ClassLoader::class.java.getDeclaredMethod(")
lines.append("                \"loadClass\", String::class.java, java.lang.Boolean.TYPE)")
lines.append("            module.hook(m).intercept { chain ->")
lines.append("                val cn = chain.args[0] as? String ?: return@intercept chain.proceed()")
lines.append("                if (cn.startsWith(\"com.tencent.mm\") && (cn.lowercase().contains(\"emoji\") || cn.lowercase().contains(\"game\") || cn.lowercase().contains(\"sticker\"))) {")
lines.append("                    module.log(Log.INFO, TAG, \"CLASS: $cn\")")
lines.append("                }")
lines.append("                chain.proceed()")
lines.append("            }")
lines.append("            module.log(Log.INFO, TAG, \"CL hooked\")")
lines.append("        } catch (e: Throwable) { module.log(Log.ERROR, TAG, \"CL: ${e.message}\") }")
lines.append("    }")
lines.append("")
lines.append("    private fun tryHookKnownTargets(cl: ClassLoader) {")
lines.append("        val cns = listOf(")
lines.append("            \"com.tencent.mm.plugin.emoji.model.EmojiInfo\",")
lines.append("            \"com.tencent.mm.plugin.emoji.model.EmojiItem\",")
lines.append("            \"com.tencent.mm.storage.emotion.EmojiInfo\",")
lines.append("            \"com.tencent.mm.storage.emotion.EmojiGroupInfo\",")
lines.append("            \"com.tencent.mm.storage.bl\",")
lines.append("            \"com.tencent.mm.storage.br\",")
lines.append("            \"com.tencent.mm.storage.bs\",")
lines.append("            \"com.tencent.mm.plugin.emoji.mgr.EmojiMgr\",")
lines.append("            \"com.tencent.mm.plugin.emoji.b.d\",")
lines.append("            \"com.tencent.mm.plugin.game.luggage\",")
lines.append("            \"com.tencent.mm.plugin.game.ui.GameMessageUI\",")
lines.append("            \"com.tencent.mm.message.AppMessage\",")
lines.append("        )")
lines.append("        for (cn in cns) {")
lines.append("            try {")
lines.append("                val cls = cl.loadClass(cn)")
lines.append("                for (m in cls.declaredMethods) {")
lines.append("                    if (m.parameterTypes.size == 1 && m.parameterTypes[0] == String::class.java) {")
lines.append("                        module.hook(m).intercept { chain ->")
lines.append("                            if (!FeatureConfig.gameCheat) return@intercept chain.proceed()")
lines.append("                            val c = chain.args[0] as String")
lines.append("                            if (isGameEmoji(c)) {")
lines.append("                                module.log(Log.INFO, TAG, \"$cn.${m.name} GAME!\")")
lines.append("                                interceptChain(chain, c)")
lines.append("                            } else chain.proceed()")
lines.append("                        }")
lines.append("                        module.log(Log.INFO, TAG, \"$cn.${m.name} hooked\")")
lines.append("                        break")
lines.append("                    }")
lines.append("                }")
lines.append("            } catch (_: Throwable) {}")
lines.append("        }")
lines.append("        try {")
lines.append("            val cf = cl.loadClass(\"com.tencent.mm.pluginsdk.ui.chat.ChatFooter\")")
lines.append("            for (m in cf.declaredMethods) {")
lines.append("                if (m.parameterTypes.size in 0..3) {")
lines.append("                    module.hook(m).intercept { chain ->")
lines.append("                        if (!FeatureConfig.gameCheat) return@intercept chain.proceed()")
lines.append("                        for (i in chain.args.indices) {")
lines.append("                            val a = chain.args[i]")
lines.append("                            if (a is String && isGameEmoji(a)) {")
lines.append("                                module.log(Log.INFO, TAG, \"CF.${m.name} GAME!\")")
lines.append("                                interceptChain(chain, a)")
lines.append("                                return@intercept null")
lines.append("                            }")
lines.append("                        }")
lines.append("                        chain.proceed()")
lines.append("                    }")
lines.append("                }")
lines.append("            }")
lines.append("            module.log(Log.INFO, TAG, \"CF hooked\")")
lines.append("        } catch (_: Throwable) {}")
lines.append("    }")
lines.append("")
lines.append("    private fun hookViewPerformClick() {")
lines.append("        try {")
lines.append("            val m = View::class.java.getDeclaredMethod(\"performClick\")")
lines.append("            module.hook(m).intercept { chain ->")
lines.append("                if (!FeatureConfig.gameCheat) return@intercept chain.proceed()")
lines.append("                val v = chain.thisObject as? View ?: return@intercept chain.proceed()")
lines.append("                val cn = v.javaClass.name")
lines.append("                val lc = cn.lowercase()")
lines.append("                if (lc.contains(\"emoji\") || lc.contains(\"game\") || lc.contains(\"sticker\")) {")
lines.append("                    val tag = v.tag")
lines.append("                    val ts = tag?.toString() ?: \"\"")
lines.append("                    if (ts.isNotEmpty() && ts.length < 500) {")
lines.append("                        module.log(Log.INFO, TAG, \"V: $cn tag=${ts.take(200)}\")")
lines.append("                        if (isGameEmoji(ts)) { interceptChain(chain, ts); return@intercept null }")
lines.append("                    } else { module.log(Log.INFO, TAG, \"V: $cn\") }")
lines.append("                }")
lines.append("                chain.proceed()")
lines.append("            }")
lines.append("            module.log(Log.INFO, TAG, \"V.click hooked\")")
lines.append("        } catch (e: Throwable) { module.log(Log.ERROR, TAG, \"V: ${e.message}\") }")
lines.append("    }")
lines.append("")
lines.append("    private fun hookAdapterViewClick() {")
lines.append("        try {")
lines.append("            val av = classLoader!!.loadClass(\"android.widget.AdapterView\")")
lines.append("            val m = av.getDeclaredMethod(\"performItemClick\", View::class.java, Integer.TYPE, java.lang.Long.TYPE)")
lines.append("            module.hook(m).intercept { chain ->")
lines.append("                if (!FeatureConfig.gameCheat) return@intercept chain.proceed()")
lines.append("                val ao = chain.thisObject")
lines.append("                val cn = ao.javaClass.name")
lines.append("                val lc = cn.lowercase()")
lines.append("                if (lc.contains(\"emoji\") || lc.contains(\"game\") || lc.contains(\"sticker\")) {")
lines.append("                    val pos = chain.args[1] as Int")
lines.append("                    try {")
lines.append("                        val ad = ao.javaClass.getMethod(\"getAdapter\").invoke(ao)")
lines.append("                        val item = ad?.javaClass?.getMethod(\"getItem\", Integer.TYPE)?.invoke(ad, pos)")
lines.append("                        val itemStr = item?.toString() ?: \"\"")
lines.append("                        module.log(Log.INFO, TAG, \"A: $cn pos=$pos item=${itemStr.take(200)}\")")
lines.append("                        if (isGameEmoji(itemStr)) { interceptChain(chain, itemStr); return@intercept null }")
lines.append("                    } catch (e: Throwable) { module.log(Log.INFO, TAG, \"A: $cn pos=$pos err=${e.message}\") }")
lines.append("                }")
lines.append("                chain.proceed()")
lines.append("            }")
lines.append("            module.log(Log.INFO, TAG, \"AV hooked\")")
lines.append("        } catch (e: Throwable) { module.log(Log.ERROR, TAG, \"AV: ${e.message}\") }")
lines.append("    }")
lines.append("")
lines.append("    private fun isGameEmoji(c: String): Boolean {")
lines.append("        if (c.length < 20) return false")
lines.append("        if (!c.contains(\"<emoji\") && !c.lowercase().contains(\"<gameext\") && !c.lowercase().contains(\"gamecontent\")) return false")
lines.append("        return c.contains(\"type=\"\"1\"\"\") || c.contains(\"type=\"\"2\"\"\") || c.lowercase().contains(\"<gameext\") || c.lowercase().contains(\"gamecontent\")")
lines.append("    }")
lines.append("")
lines.append("    private fun interceptChain(chain: Any, content: String) {")
lines.append("        blockedChain = chain; blockedContent = content")
lines.append("        val gt = if (content.contains(\"type=\"\"2\"\"\")) 2 else 1")
lines.append("        mainHandler.post { showPicker(gt) }")
lines.append("    }")
lines.append("")
lines.append("    private fun showPicker(gameType: Int) {")
lines.append("        val ctx = tryGetActivity() ?: run { proceedBlocked(); return }")
lines.append("        val title = if (gameType == 2) \"Pick Dice (1-6)\" else \"Pick RPS\"")
lines.append("        val items = if (gameType == 2) arrayOf(\"1\",\"2\",\"3\",\"4\",\"5\",\"6\") else arrayOf(\"Rock\",\"Scissors\",\"Paper\")")
lines.append("        AlertDialog.Builder(ctx).setTitle(title).setItems(items) { _, which ->")
lines.append("            val chosen = if (gameType == 2) which + 1 else when (which) { 0 -> 2; 1 -> 1; 2 -> 0; else -> 0 }")
lines.append("            replaceContent(chosen, gameType)")
lines.append("        }.setOnCancelListener { proceedBlocked() }.show()")
lines.append("    }")
lines.append("")
lines.append("    private fun replaceContent(chosen: Int, gameType: Int) {")
lines.append("        try {")
lines.append("            val chain = blockedChain ?: return")
lines.append("            val c = blockedContent ?: return")
lines.append("            val nc = if (gameType == 2) c.replace(Regex(\"content=\"\"\\\\d+\"\"\"), \"content=\"\"$chosen\"\"\")")
lines.append("                     else c.replace(Regex(\"type=\"\"\\\\d+\"\"\"), \"type=\"\"$chosen\"\"\")")
lines.append("            try {")
lines.append("                val af = chain.javaClass.getDeclaredField(\"args\"); af.isAccessible = true")
lines.append("                val args = af.get(chain) as Array<Any?>; args[0] = nc")
lines.append("                chain.javaClass.getMethod(\"proceed\").invoke(chain)")
lines.append("            } catch (_: Throwable) { chain.javaClass.getMethod(\"proceed\").invoke(chain) }")
lines.append("            module.log(Log.INFO, TAG, \"Cheat: t=$gameType v=$chosen\")")
lines.append("        } catch (e: Throwable) { module.log(Log.ERROR, TAG, \"replace: ${e.message}\"); proceedBlocked() }")
lines.append("        finally { blockedChain = null; blockedContent = null }")
lines.append("    }")
lines.append("")
lines.append("    private fun proceedBlocked() {")
lines.append("        try { blockedChain?.javaClass?.getMethod(\"proceed\")?.invoke(blockedChain) } catch (_: Throwable) {}")
lines.append("        blockedChain = null; blockedContent = null")
lines.append("    }")
lines.append("")
lines.append("    private fun tryGetActivity(): android.app.Activity? {")
lines.append("        return try {")
lines.append("            val c = Class.forName(\"android.app.ActivityThread\")")
lines.append("            val am = c.getDeclaredMethod(\"currentActivityThread\").invoke(null)")
lines.append("            val f = c.getDeclaredField(\"mActivities\"); f.isAccessible = true")
lines.append("            @Suppress(\"UNCHECKED_CAST\")")
lines.append("            val acts = f.get(am) as? Map<Any, Any>")
lines.append("            if (acts != null) for (rec in acts.values) {")
lines.append("                val af = rec.javaClass.getDeclaredField(\"activity\"); af.isAccessible = true")
lines.append("                val a = af.get(rec)")
lines.append("                if (a is android.app.Activity && !a.isFinishing) return a")
lines.append("            }")
lines.append("            null")
lines.append("        } catch (_: Throwable) { null }")
lines.append("    }")
lines.append("}")
with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print("OK")