package o45;

/* loaded from: classes16.dex */
public abstract class vf {

    /* renamed from: a, reason: collision with root package name */
    public static java.util.Map f343013a;

    /* renamed from: b, reason: collision with root package name */
    public static final java.lang.String[] f343014b = (java.lang.String[]) new o45.d().toArray(new java.lang.String[0]);

    public static android.os.Bundle a(boolean z17, java.lang.String str) {
        android.os.Bundle bundle = new android.os.Bundle();
        bundle.putBoolean("handle", true);
        bundle.putString("handle_result", str);
        return bundle;
    }

    public static o45.m b(java.lang.String str) {
        java.util.Map map = f343013a;
        if (map == null || ((java.util.HashMap) map).size() <= 0) {
            java.util.HashMap hashMap = new java.util.HashMap(128);
            f343013a = hashMap;
            hashMap.put("log", new o45.b6());
            ((java.util.HashMap) f343013a).put("imagePreview", new o45.i5());
            ((java.util.HashMap) f343013a).put(com.google.android.gms.common.Scopes.PROFILE, new o45.j9());
            ((java.util.HashMap) f343013a).put("shareWeibo", new o45.ve());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.share.g1.NAME, new o45.xd());
            ((java.util.HashMap) f343013a).put("shareTimelinePrivate", new o45.yd());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.z1.NAME, new o45.u());
            ((java.util.HashMap) f343013a).put("streamingVideoPlay", new o45.ud());
            ((java.util.HashMap) f343013a).put("addContact", new o45.n());
            ((java.util.HashMap) f343013a).put("getWidgetCaptureImgUrl", new o45.q4());
            ((java.util.HashMap) f343013a).put("sendAppMessage", new o45.fb());
            ((java.util.HashMap) f343013a).put("sendAppMessagePrivate", new o45.gb());
            ((java.util.HashMap) f343013a).put(be1.a1.NAME, new o45.pe());
            ((java.util.HashMap) f343013a).put("scanQRCode", new o45.ua());
            ((java.util.HashMap) f343013a).put("hideOptionMenu", new o45.f5());
            ((java.util.HashMap) f343013a).put("showOptionMenu", new o45.xc());
            ((java.util.HashMap) f343013a).put(be1.z.NAME, new o45.n3());
            ((java.util.HashMap) f343013a).put("closeWindow", new o45.y0());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.appdownload.g0.NAME, new o45.i3());
            ((java.util.HashMap) f343013a).put("setFontSizeCallback", new o45.wb());
            ((java.util.HashMap) f343013a).put("jumpToInstallUrl", new o45.p5());
            ((java.util.HashMap) f343013a).put("launchApp", new o45.w5());
            ((java.util.HashMap) f343013a).put("getBrandWCPayRequest", new o45.r2());
            ((java.util.HashMap) f343013a).put(yc1.f0.NAME, new o45.xa());
            ((java.util.HashMap) f343013a).put(yc1.u.NAME, new o45.f6());
            ((java.util.HashMap) f343013a).put("requestHKCashier", new o45.ia());
            ((java.util.HashMap) f343013a).put("wcpaySecurityCrosscutBack", new o45.re());
            ((java.util.HashMap) f343013a).put("editAddress", new o45.u1());
            ((java.util.HashMap) f343013a).put("getHeadingAndPitch", new o45.f3());
            ((java.util.HashMap) f343013a).put("sendEmail", new o45.lb());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.appdownload.q.NAME, new o45.q());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.appdownload.x.NAME, new o45.e0());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.appdownload.h1.NAME, new o45.x8());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.pc.NAME, new o45.qa());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.appdownload.l1.NAME, new o45.m9());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.appdownload.m0.NAME, new o45.l5());
            ((java.util.HashMap) f343013a).put("getLatestAddress", new o45.u3());
            ((java.util.HashMap) f343013a).put("openSpecificView", new o45.e8());
            ((java.util.HashMap) f343013a).put("jumpWCMall", new o45.r5());
            ((java.util.HashMap) f343013a).put("launch3rdApp", new o45.v5());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.cf.NAME, new o45.cf());
            ((java.util.HashMap) f343013a).put("openUrlByExtBrowser", new o45.f8());
            ((java.util.HashMap) f343013a).put("geoLocation", new o45.l2());
            ((java.util.HashMap) f343013a).put("getBrandWCPayBindCardRequest", new o45.q2());
            ((java.util.HashMap) f343013a).put("openProductView", new o45.x7());
            ((java.util.HashMap) f343013a).put("openProductViewWithPid", new o45.y7());
            ((java.util.HashMap) f343013a).put("jumpToBizProfile", new o45.q5());
            ((java.util.HashMap) f343013a).put("openTimelineCheckInList", new o45.j6());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.lbs.g0.NAME, new o45.i6());
            ((java.util.HashMap) f343013a).put("timelineCheckIn", new o45.h6());
            ((java.util.HashMap) f343013a).put("getBrandWCPayCreateCreditCardRequest", new o45.m8());
            ((java.util.HashMap) f343013a).put("chooseCard", new o45.k0());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.s4.NAME, new o45.o0());
            ((java.util.HashMap) f343013a).put("sendServiceAppMessage", new o45.nb());
            ((java.util.HashMap) f343013a).put("musicPlay", new o45.e6());
            ((java.util.HashMap) f343013a).put("mmsf0001", new o45.w2());
            ((java.util.HashMap) f343013a).put("getTransferMoneyRequest", new o45.l4());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.pay.m0.NAME, new o45.h8());
            ((java.util.HashMap) f343013a).put("setCloseWindowConfirmDialogInfo", new o45.ub());
            ((java.util.HashMap) f343013a).put("batchAddCard", new o45.y());
            ((java.util.HashMap) f343013a).put("preVerifyJSAPI", new o45.g9());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.audio.d3.NAME, new o45.ld());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.audio.l3.NAME, new o45.rd());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.audio.v2.NAME, new o45.b9());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.audio.y1.NAME, new o45.y8());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.audio.h3.NAME, new o45.td());
            ((java.util.HashMap) f343013a).put("uploadVoice", new o45.me());
            ((java.util.HashMap) f343013a).put("downloadVoice", new o45.q1());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.media.e3.NAME, new o45.n0());
            ((java.util.HashMap) f343013a).put("uploadImage", new o45.je());
            ((java.util.HashMap) f343013a).put("downloadImage", new o45.o1());
            ((java.util.HashMap) f343013a).put("uploadMediaFile", new o45.ke());
            ((java.util.HashMap) f343013a).put("hideMenuItems", new o45.c5());
            ((java.util.HashMap) f343013a).put("showMenuItems", new o45.uc());
            ((java.util.HashMap) f343013a).put("hideAllNonBaseMenuItem", new o45.b5());
            ((java.util.HashMap) f343013a).put("showAllNonBaseMenuItem", new o45.pc());
            ((java.util.HashMap) f343013a).put("checkJsApi", new o45.j0());
            ((java.util.HashMap) f343013a).put("translateVoice", new o45.zd());
            ((java.util.HashMap) f343013a).put("shareQQ", new o45.mc());
            ((java.util.HashMap) f343013a).put("shareWeiboApp", new o45.oc());
            ((java.util.HashMap) f343013a).put("shareQZone", new o45.nc());
            ((java.util.HashMap) f343013a).put("getSendC2CMessageRequest", new o45.h4());
            ((java.util.HashMap) f343013a).put("batchViewCard", new o45.b0());
            ((java.util.HashMap) f343013a).put("configWXDeviceWiFi", new o45.b1());
            ((java.util.HashMap) f343013a).put("getCurrentSSID", new o45.u2());
            ((java.util.HashMap) f343013a).put("setPageOwner", new o45.cc());
            ((java.util.HashMap) f343013a).put("getWechatVerifyTicket", new o45.o4());
            ((java.util.HashMap) f343013a).put("openWXDeviceLib", new o45.n8());
            ((java.util.HashMap) f343013a).put("startScanWXDevice", new o45.md());
            ((java.util.HashMap) f343013a).put("stopScanWXDevice", new o45.sd());
            ((java.util.HashMap) f343013a).put("connectWXDevice", new o45.d1());
            ((java.util.HashMap) f343013a).put("disconnectWXDevice", new o45.n1());
            ((java.util.HashMap) f343013a).put("getWXDeviceTicket", new o45.s4());
            ((java.util.HashMap) f343013a).put("getWXDeviceInfos", new o45.r4());
            ((java.util.HashMap) f343013a).put("sendDataToWXDevice", new o45.ib());
            ((java.util.HashMap) f343013a).put("closeWXDeviceLib", new o45.a1());
            ((java.util.HashMap) f343013a).put("setSendDataDirection", new o45.gc());
            ((java.util.HashMap) f343013a).put("verifyWCPayPassword", new o45.oe());
            ((java.util.HashMap) f343013a).put("getPaymentOrderRequest", new o45.t3());
            ((java.util.HashMap) f343013a).put("openGameDetail", new o45.l7());
            ((java.util.HashMap) f343013a).put("openGameCenter", new o45.k7());
            ((java.util.HashMap) f343013a).put("setGameDebugConfig", new o45.xb());
            ((java.util.HashMap) f343013a).put("startTempSession", new o45.od());
            ((java.util.HashMap) f343013a).put("getH5PrepayRequest", new o45.g3());
            ((java.util.HashMap) f343013a).put("getH5TransactionRequest", new o45.h3());
            ((java.util.HashMap) f343013a).put("menu:share:timeline", new o45.of());
            ((java.util.HashMap) f343013a).put("menu:share:appmessage", new o45.lf());
            ((java.util.HashMap) f343013a).put("menu:share:qq", new o45.mf());
            ((java.util.HashMap) f343013a).put("menu:share:weiboApp", new o45.pf());
            ((java.util.HashMap) f343013a).put("menu:setfont", new o45.kf());
            ((java.util.HashMap) f343013a).put("menu:share:weibo", new o45.pf());
            ((java.util.HashMap) f343013a).put("menu:share:QZone", new o45.nf());
            ((java.util.HashMap) f343013a).put("getRecevieBizHongBaoRequest", new o45.k());
            ((java.util.HashMap) f343013a).put("openCamera", new o45.w6());
            ((java.util.HashMap) f343013a).put("insertVideoPlayer", new o45.k5());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.video.jsapi.m.NAME, new o45.ge());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.video.jsapi.l.NAME, new o45.v9());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.video.jsapi.h.NAME, new o45.t8());
            ((java.util.HashMap) f343013a).put("deleteSearchHistory", new o45.k1());
            ((java.util.HashMap) f343013a).put("getSearchHistory", new o45.d4());
            ((java.util.HashMap) f343013a).put("getSearchData", new o45.z3());
            ((java.util.HashMap) f343013a).put("showWeDrawHomeView", new o45.ed());
            ((java.util.HashMap) f343013a).put("getFestivalLiveInfo", new o45.b3());
            ((java.util.HashMap) f343013a).put("getChatSearchData", new o45.s2());
            ((java.util.HashMap) f343013a).put("getPoiInfo", new o45.e3());
            ((java.util.HashMap) f343013a).put("updateReddotTimeStamps", new o45.ce());
            ((java.util.HashMap) f343013a).put("getTeachSearchData", new o45.j4());
            ((java.util.HashMap) f343013a).put("getSearchGuideData", new o45.c4());
            ((java.util.HashMap) f343013a).put("getSearchAvatarList", new o45.y3());
            ((java.util.HashMap) f343013a).put("getSearchSnsImageList", new o45.f4());
            ((java.util.HashMap) f343013a).put("getSearchImageList", new o45.e4());
            ((java.util.HashMap) f343013a).put("getSearchDisplayNameList", new o45.a4());
            ((java.util.HashMap) f343013a).put("startSearchItemDetailPage", new o45.nd());
            ((java.util.HashMap) f343013a).put("startCommonSearchItemDetailPage", new o45.id());
            ((java.util.HashMap) f343013a).put("reportSearchStatistics", new o45.ca());
            ((java.util.HashMap) f343013a).put("reportSearchRealTimeStatistics", new o45.ba());
            ((java.util.HashMap) f343013a).put("searchDataHasResult", new o45.wa());
            ((java.util.HashMap) f343013a).put("openEmotionPage", new o45.g2());
            ((java.util.HashMap) f343013a).put("getSearchSuggestionData", new o45.g4());
            ((java.util.HashMap) f343013a).put("setSearchInputWord", new o45.fc());
            ((java.util.HashMap) f343013a).put("setSnsObjectXmlDescList", new o45.hc());
            ((java.util.HashMap) f343013a).put("clickSnsMusicPlayButton", new o45.x0());
            ((java.util.HashMap) f343013a).put("openWeAppPage", new o45.l8());
            ((java.util.HashMap) f343013a).put("openWeAppForWebSearch", new o45.k8());
            ((java.util.HashMap) f343013a).put("reportWeAppSearchRealtime", new o45.we());
            ((java.util.HashMap) f343013a).put("doSearchOperation", new o45.t1());
            ((java.util.HashMap) f343013a).put("insertSearchWAWidgetView", new o45.j5());
            ((java.util.HashMap) f343013a).put("removeSearchWAWidgetView", new o45.u9());
            ((java.util.HashMap) f343013a).put("updateSearchWAWidgetView", new o45.ee());
            ((java.util.HashMap) f343013a).put("showSearchActionSheet", new o45.yc());
            ((java.util.HashMap) f343013a).put("cancelSearchActionSheet", new o45.g0());
            ((java.util.HashMap) f343013a).put("showSearchToast", new o45.bd());
            ((java.util.HashMap) f343013a).put("showSearchLoading", new o45.zc());
            ((java.util.HashMap) f343013a).put("hideSearchLoading", new o45.g5());
            ((java.util.HashMap) f343013a).put("updateWASearchTemplate", new o45.he());
            ((java.util.HashMap) f343013a).put("preloadSearchWeapp", new o45.e9());
            ((java.util.HashMap) f343013a).put("uxSearchOpLog", new o45.ne());
            ((java.util.HashMap) f343013a).put("querySearchWeb", new o45.i2());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.finder.h0.NAME, new o45.j7());
            ((java.util.HashMap) f343013a).put("playMusic", new o45.a9());
            ((java.util.HashMap) f343013a).put("openMusicPage", new o45.t7());
            ((java.util.HashMap) f343013a).put("openFinderFeed", new o45.h7());
            ((java.util.HashMap) f343013a).put("getNewLifeContact", new o45.o3());
            ((java.util.HashMap) f343013a).put("getCurrentLocation", new o45.t2());
            ((java.util.HashMap) f343013a).put("navControl", new o45.g6());
            ((java.util.HashMap) f343013a).put("setInteractivePopGestureEnabled", new o45.yb());
            ((java.util.HashMap) f343013a).put("showNavBarShadow", new o45.wc());
            ((java.util.HashMap) f343013a).put("hideNavBarShadow", new o45.e5());
            ((java.util.HashMap) f343013a).put("jumpToWXWallet", new o45.t5());
            ((java.util.HashMap) f343013a).put("scanCover", new o45.l());
            ((java.util.HashMap) f343013a).put("reportActionInfo", new o45.w9());
            ((java.util.HashMap) f343013a).put("openMyDeviceProfile", new o45.u7());
            ((java.util.HashMap) f343013a).put("selectPedometerSource", new o45.cb());
            ((java.util.HashMap) f343013a).put("nfcIsConnect", new o45.p6());
            ((java.util.HashMap) f343013a).put("nfcConnect", new o45.m6());
            ((java.util.HashMap) f343013a).put("nfcTransceive", new o45.q6());
            ((java.util.HashMap) f343013a).put("nfcBatchTransceive", new o45.k6());
            ((java.util.HashMap) f343013a).put("nfcGetId", new o45.n6());
            ((java.util.HashMap) f343013a).put("nfcGetInfo", new o45.o6());
            ((java.util.HashMap) f343013a).put("startMonitoringBeacons", new o45.jd());
            ((java.util.HashMap) f343013a).put("stopMonitoringBeacons", new o45.pd());
            ((java.util.HashMap) f343013a).put("nfcCheckState", new o45.l6());
            ((java.util.HashMap) f343013a).put("getWebPayCheckoutCounterRequst", new o45.a6());
            ((java.util.HashMap) f343013a).put("addCustomMenuItems", new o45.o());
            ((java.util.HashMap) f343013a).put("operateGameCenterMsg", new o45.q8());
            ((java.util.HashMap) f343013a).put("openEnterpriseChat", new o45.f7());
            ((java.util.HashMap) f343013a).put("enterEnterpriseChat", new o45.y1());
            ((java.util.HashMap) f343013a).put("openEnterpriseContact", new o45.g7());
            ((java.util.HashMap) f343013a).put("selectEnterpriseContact", new o45.ab());
            ((java.util.HashMap) f343013a).put("getEnterpriseChat", new o45.a3());
            ((java.util.HashMap) f343013a).put("reportIDKey", new o45.z9());
            ((java.util.HashMap) f343013a).put("quicklyAddBrandContact", new o45.p9());
            ((java.util.HashMap) f343013a).put("consumedShareCard", new o45.e1());
            ((java.util.HashMap) f343013a).put("cache", new o45.te());
            ((java.util.HashMap) f343013a).put("publicCache", new o45.ue());
            ((java.util.HashMap) f343013a).put(vd1.h.NAME, new o45.u5());
            ((java.util.HashMap) f343013a).put("realtimeReport", new o45.r9());
            ((java.util.HashMap) f343013a).put("openUrlWithExtraWebview", new o45.g8());
            ((java.util.HashMap) f343013a).put("selectSingleContact", new o45.db());
            ((java.util.HashMap) f343013a).put("sendAppMessageToSpecifiedContact", new o45.eb());
            ((java.util.HashMap) f343013a).put("setLocalData", new o45.zb());
            ((java.util.HashMap) f343013a).put("getLocalData", new o45.j3());
            ((java.util.HashMap) f343013a).put("clearLocalData", new o45.v0());
            ((java.util.HashMap) f343013a).put(qc1.v.NAME, new o45.sc());
            ((java.util.HashMap) f343013a).put("openBizPublishImage", new o45.v6());
            ((java.util.HashMap) f343013a).put("showBottomToast", new o45.qc());
            ((java.util.HashMap) f343013a).put("shareCustomContent", new o45.kc());
            ((java.util.HashMap) f343013a).put(hc1.i.NAME, new o45.cd());
            ((java.util.HashMap) f343013a).put("disableBounceScroll", new o45.l1());
            ((java.util.HashMap) f343013a).put("clearBounceBackground", new o45.t0());
            ((java.util.HashMap) f343013a).put("setNavigationBarButtons", new o45.ac());
            ((java.util.HashMap) f343013a).put("enableFullScreen", new o45.w1());
            ((java.util.HashMap) f343013a).put(nd1.c2.NAME, new o45.vc());
            ((java.util.HashMap) f343013a).put(nd1.j.NAME, new o45.d5());
            ((java.util.HashMap) f343013a).put("enablePullDownRefresh", new o45.x1());
            ((java.util.HashMap) f343013a).put(nd1.f2.NAME, new o45.kd());
            ((java.util.HashMap) f343013a).put(nd1.g2.NAME, new o45.qd());
            ((java.util.HashMap) f343013a).put("disablePullDownRefresh", new o45.m1());
            ((java.util.HashMap) f343013a).put("setPageTitle", new o45.dc());
            ((java.util.HashMap) f343013a).put("setStatusBarStyle", new o45.ic());
            ((java.util.HashMap) f343013a).put("deleteAccountSuccess", new o45.j1());
            ((java.util.HashMap) f343013a).put("chooseVideo", new o45.s0());
            ((java.util.HashMap) f343013a).put("uploadVideo", new o45.le());
            ((java.util.HashMap) f343013a).put("openMapNavigateMenu", new o45.s7());
            ((java.util.HashMap) f343013a).put(nd1.d1.NAME, new o45.bc());
            ((java.util.HashMap) f343013a).put("getWCPayRealnameVerify", new o45.n4());
            ((java.util.HashMap) f343013a).put("openDesignerEmojiView", new o45.z6());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.emoji.m.NAME, new o45.b7());
            ((java.util.HashMap) f343013a).put("openEmoticonTopicList", new o45.e7());
            ((java.util.HashMap) f343013a).put("openDesignerEmojiViewLocal", new o45.a7());
            ((java.util.HashMap) f343013a).put("openDesignerProfileLocal", new o45.c7());
            ((java.util.HashMap) f343013a).put("openEmotionDetailViewLocal", new o45.j());
            ((java.util.HashMap) f343013a).put("openNewPage", new o45.v7());
            ((java.util.HashMap) f343013a).put("getSearchEmotionData", new o45.b4());
            ((java.util.HashMap) f343013a).put("openEmotionUrl", new o45.v1());
            ((java.util.HashMap) f343013a).put("WNNativeCallbackOnClick", new o45.af());
            ((java.util.HashMap) f343013a).put("WNNativeCallbackOnLongClick", new o45.bf());
            ((java.util.HashMap) f343013a).put("WNNativeCallbackOnCaretChange", new o45.ze());
            ((java.util.HashMap) f343013a).put("WNNativeCallbackInitData", new o45.ye());
            ((java.util.HashMap) f343013a).put("WNNativeAsyncCallback", new o45.xe());
            ((java.util.HashMap) f343013a).put("WNNativeCallbackOnBecomeEditing", new o45.hf());
            ((java.util.HashMap) f343013a).put("WNNativeCallbackOnBecomeEdited", new o45.Cif());
            ((java.util.HashMap) f343013a).put("changePayActivityView", new o45.h0());
            ((java.util.HashMap) f343013a).put("selectWalletCurrency", new o45.vd());
            ((java.util.HashMap) f343013a).put("scanLicence", new o45.ta());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.audio.e1.NAME, new o45.f());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.audio.g0.NAME, new o45.e());
            ((java.util.HashMap) f343013a).put("clearWebviewCache", new o45.w0());
            ((java.util.HashMap) f343013a).put("requireSoterBiometricAuthentication", new o45.gd());
            ((java.util.HashMap) f343013a).put("getSupportSoter", new o45.hd());
            ((java.util.HashMap) f343013a).put("unbindBankCard", new o45.ae());
            ((java.util.HashMap) f343013a).put("setBounceBackground", new o45.tb());
            ((java.util.HashMap) f343013a).put("sendEnterpriseChat", new o45.jb());
            ((java.util.HashMap) f343013a).put("doExposePreparation", new o45.s1());
            ((java.util.HashMap) f343013a).put("getMsgProofItems", new o45.m3());
            ((java.util.HashMap) f343013a).put("openSecurityView", new o45.c8());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.u4.NAME, new o45.p0());
            ((java.util.HashMap) f343013a).put("getOpenDeviceId", new o45.q3());
            ((java.util.HashMap) f343013a).put("getOpenDeviceUUID", new o45.r3());
            ((java.util.HashMap) f343013a).put("getRouteUrl", new o45.x3());
            ((java.util.HashMap) f343013a).put("idCardRealnameVerify", new o45.h5());
            ((java.util.HashMap) f343013a).put("uploadIdCardSuccess", new o45.tf());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.picker.l.NAME, new o45.rc());
            ((java.util.HashMap) f343013a).put("openLuckyMoneyDetailView", new o45.q7());
            ((java.util.HashMap) f343013a).put("resendRemittanceMsg", new o45.pa());
            ((java.util.HashMap) f343013a).put("getGameCommInfo", new o45.d3());
            ((java.util.HashMap) f343013a).put("openGameRegion", new o45.m7());
            ((java.util.HashMap) f343013a).put("chooseIdCard", new o45.m0());
            ((java.util.HashMap) f343013a).put("getLocalImgData", new o45.g());
            ((java.util.HashMap) f343013a).put("openWeApp", new o45.j8());
            ((java.util.HashMap) f343013a).put("recordVideo", new o45.s9());
            ((java.util.HashMap) f343013a).put("previewVideo", new o45.f9());
            ((java.util.HashMap) f343013a).put("uploadEncryptMediaFile", new o45.ie());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.media.z3.NAME, new o45.q0());
            ((java.util.HashMap) f343013a).put("requestWxFacePictureVerify", new o45.b2());
            ((java.util.HashMap) f343013a).put("openCustomWebview", new o45.y6());
            ((java.util.HashMap) f343013a).put("forceUpdateWxaAttr", new o45.f2());
            ((java.util.HashMap) f343013a).put("openLuckyMoneyHistory", new o45.r7());
            ((java.util.HashMap) f343013a).put("menuitem:gameSendDesktop", new o45.kb());
            ((java.util.HashMap) f343013a).put("getWePkgAuthResult", new o45.p4());
            ((java.util.HashMap) f343013a).put("getLocalWePkgInfo", new o45.k3());
            ((java.util.HashMap) f343013a).put("openGameWebView", new o45.o7());
            ((java.util.HashMap) f343013a).put("reportGameWeb", new o45.y9());
            ((java.util.HashMap) f343013a).put("launchApplication", new o45.x5());
            ((java.util.HashMap) f343013a).put("showSearchOfBizHistory", new o45.ad());
            ((java.util.HashMap) f343013a).put("login", new o45.c6());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.auth.o1.NAME, new o45.x());
            ((java.util.HashMap) f343013a).put("requestWxFacePictureVerifyUnionVideo", new o45.c2());
            ((java.util.HashMap) f343013a).put("checkIsSupportFaceDetect", new o45.i0());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.bio.face.p.NAME, new o45.ga());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.bio.face.q.NAME, new o45.ha());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.audio.p0.NAME, new o45.p8());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.audio.e2.NAME, new o45.rb());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.audio.e0.NAME, new o45.o2());
            ((java.util.HashMap) f343013a).put("setBackgroundAudioStateMV", new o45.sb());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.appdownload.v.NAME, new o45.r());
            ((java.util.HashMap) f343013a).put("setScreenOrientation", new o45.ec());
            ((java.util.HashMap) f343013a).put("addToEmoticon", new o45.t());
            ((java.util.HashMap) f343013a).put("shareEmoticon", new o45.lc());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.z7.NAME, new o45.d6());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.advertise.r.NAME, new o45.x6());
            ((java.util.HashMap) f343013a).put("openSearchCanvas", new o45.z7());
            ((java.util.HashMap) f343013a).put("opVoteAdData", new o45.w8());
            ((java.util.HashMap) f343013a).put("opJumpView", new o45.v8());
            ((java.util.HashMap) f343013a).put("opAdH5Func", new o45.u8());
            ((java.util.HashMap) f343013a).put("requestWxFaceRegisterInternal", new o45.ma());
            ((java.util.HashMap) f343013a).put("requestWxFaceVerifyInternal", new o45.na());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.l.NAME, new o45.z5());
            ((java.util.HashMap) f343013a).put("openFinderProduct", new o45.i7());
            ((java.util.HashMap) f343013a).put("reportMiniProgramPageData", new o45.aa());
            ((java.util.HashMap) f343013a).put("selectContact", new o45.ya());
            ((java.util.HashMap) f343013a).put("openSearchWAWidgetLogView", new o45.a8());
            ((java.util.HashMap) f343013a).put("reloadSearchWAWidgetData", new o45.t9());
            ((java.util.HashMap) f343013a).put("gotoEmoticonPad", new o45.t4());
            ((java.util.HashMap) f343013a).put("querySimilarEmotion", new o45.o9());
            ((java.util.HashMap) f343013a).put("closeWindowAndGoNext", new o45.z0());
            ((java.util.HashMap) f343013a).put("requestWxVoicePrintVerifyInternal", new o45.oa());
            ((java.util.HashMap) f343013a).put("openBizChat", new o45.u6());
            ((java.util.HashMap) f343013a).put("handleWCPayWalletBuffer", new o45.a5());
            ((java.util.HashMap) f343013a).put("tapSearchWAWidgetView", new o45.wd());
            ((java.util.HashMap) f343013a).put("getMatchContactList", new o45.l3());
            ((java.util.HashMap) f343013a).put("openSearchWebView", new o45.b8());
            ((java.util.HashMap) f343013a).put("openWXSearchPage", new o45.o8());
            ((java.util.HashMap) f343013a).put("viewTypeChange", new o45.qe());
            ((java.util.HashMap) f343013a).put(pf1.f.NAME, new o45.n5());
            ((java.util.HashMap) f343013a).put("openGameUrlWithExtraWebView", new o45.n7());
            ((java.util.HashMap) f343013a).put("setGameData", new o45.vb());
            ((java.util.HashMap) f343013a).put("getGameData", new o45.v2());
            ((java.util.HashMap) f343013a).put("clearGameData", new o45.u0());
            ((java.util.HashMap) f343013a).put("openECard", new o45.d7());
            ((java.util.HashMap) f343013a).put("reportGamePageTime", new o45.x9());
            ((java.util.HashMap) f343013a).put("setWCPayPassword", new o45.qb());
            ((java.util.HashMap) f343013a).put("openWCPayCardList", new o45.t6());
            ((java.util.HashMap) f343013a).put("bindEmail", new o45.c0());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.w9.NAME, new o45.w7());
            ((java.util.HashMap) f343013a).put("bindEmail", new o45.c0());
            ((java.util.HashMap) f343013a).put("doGoToRecVideoList", new o45.v3());
            ((java.util.HashMap) f343013a).put("jumpWSRecVideoList", new o45.jf());
            ((java.util.HashMap) f343013a).put("openWebSearchOutLinkItem", new o45.qf());
            ((java.util.HashMap) f343013a).put("recordHistory", new o45.j2());
            for (o45.m mVar : c()) {
                ((java.util.HashMap) f343013a).put(mVar.b(), mVar);
            }
            ((java.util.HashMap) f343013a).put("getSystemInfo", new o45.i4());
            ((java.util.HashMap) f343013a).put("serviceClick", new o45.pb());
            ((java.util.HashMap) f343013a).put(cb1.o0.NAME, new o45.gf());
            ((java.util.HashMap) f343013a).put("sendSingleAppMessage", new o45.ob());
            ((java.util.HashMap) f343013a).put("wcPrivacyPolicyResult", new o45.se());
            ((java.util.HashMap) f343013a).put("currentMpInfo", new o45.g1());
            ((java.util.HashMap) f343013a).put("updateAppMessageShareData", new o45.de());
            ((java.util.HashMap) f343013a).put("updateTimelineShareData", new o45.fe());
            ((java.util.HashMap) f343013a).put("getCCData", new o45.ef());
            ((java.util.HashMap) f343013a).put("calRqt", new o45.df());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.bio.face.j.NAME, new o45.d2());
            ((java.util.HashMap) f343013a).put("request", new o45.ea());
            ((java.util.HashMap) f343013a).put("notifyPageInfo", new o45.r6());
            ((java.util.HashMap) f343013a).put("updatePageAuth", new o45.be());
            ((java.util.HashMap) f343013a).put("jumpDownloaderWidget", new o45.o5());
            ((java.util.HashMap) f343013a).put("batchUpdateWepkg", new o45.a0());
            ((java.util.HashMap) f343013a).put("addGameDownloadTask", new o45.s());
            ((java.util.HashMap) f343013a).put("internelWxFaceVerify", new o45.m5());
            ((java.util.HashMap) f343013a).put("getDownloadWidgetTaskInfos", new o45.y2());
            ((java.util.HashMap) f343013a).put("chooseHaowanMedia", new o45.l0());
            ((java.util.HashMap) f343013a).put("queryHaowanPublish", new o45.n9());
            ((java.util.HashMap) f343013a).put("publishHaowanEdition", new o45.k9());
            ((java.util.HashMap) f343013a).put("cancelHaowanPublish", new o45.f0());
            ((java.util.HashMap) f343013a).put("launchGameVideoEditor", new o45.y5());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.pay.p1.NAME, new o45.ja());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.pay.g0.NAME, new o45.d8());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.pay.h1.NAME, new o45.fa());
            ((java.util.HashMap) f343013a).put("requestOverlayPermission", new o45.ka());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.wccoin.q.NAME, new o45.ff());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.wccoin.s.NAME, new o45.f1());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.wccoin.y.NAME, new o45.dd());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.wccoin.u.NAME, new o45.z1());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.c6.NAME, new o45.p3());
            ((java.util.HashMap) f343013a).put("qqMailLoginResult", new o45.l9());
            ((java.util.HashMap) f343013a).put("getFinderLivePreviewUrl", new o45.c3());
            ((java.util.HashMap) f343013a).put("getFinderLivePreviewMicCover", new o45.c3());
            ((java.util.HashMap) f343013a).put("enterWeappContact", new o45.a2());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.u5.NAME, new o45.k2());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.pay.p0.NAME, new o45.q9());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.yc.NAME, new o45.rf());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.pay.s.NAME, new o45.z2());
            ((java.util.HashMap) f343013a).put("scanBankCard", new o45.sa());
            ((java.util.HashMap) f343013a).put("jumpToTabFind", new o45.s5());
            ((java.util.HashMap) f343013a).put("getDiscoverEntranceStatus", new o45.x2());
            ((java.util.HashMap) f343013a).put("operateStar", new o45.r8());
            ((java.util.HashMap) f343013a).put(com.tencent.mm.plugin.appbrand.jsapi.pay.q.NAME, new o45.m2());
            ((java.util.HashMap) f343013a).put("showMenu", new o45.tc());
            ((java.util.HashMap) f343013a).put("sdkCgiReport", new o45.va());
            ((java.util.HashMap) f343013a).put("SimAuth", new o45.fd());
            ((java.util.HashMap) f343013a).put("bindPhone", new o45.d0());
            ((java.util.HashMap) f343013a).put("sendPcRemindMsg", new o45.mb());
            ((java.util.HashMap) f343013a).put("downloadMediaByUrl", new o45.p1());
            ((java.util.HashMap) f343013a).put("reportSecureAction", new o45.da());
            ((java.util.HashMap) f343013a).put("getWAServiceVoipRecordLocalId", new o45.m4());
            ((java.util.HashMap) f343013a).put("sameNetVerify", new o45.ra());
            ((java.util.HashMap) f343013a).put("gotoSetting", new o45.u4());
            ((java.util.HashMap) f343013a).put("selectContacts", new o45.za());
            ((java.util.HashMap) f343013a).put("selectMultiSessionHistory", new o45.bb());
        }
        return (o45.m) ((java.util.HashMap) f343013a).get(str);
    }

    public static java.util.List c() {
        java.util.LinkedList linkedList = new java.util.LinkedList();
        linkedList.add(new o45.i1());
        linkedList.add(new o45.h1());
        linkedList.add(new o45.n2());
        linkedList.add(new o45.z4());
        linkedList.add(new o45.v4());
        linkedList.add(new o45.d9());
        linkedList.add(new o45.c9());
        linkedList.add(new o45.hb());
        linkedList.add(new o45.x4());
        linkedList.add(new o45.y4());
        linkedList.add(new o45.p());
        linkedList.add(new o45.i9());
        linkedList.add(new o45.h9());
        linkedList.add(new o45.h2());
        linkedList.add(new o45.i8());
        linkedList.add(new o45.c1());
        linkedList.add(new o45.s3());
        linkedList.add(new o45.w3());
        linkedList.add(new o45.z());
        linkedList.add(new o45.s6());
        linkedList.add(new o45.z8());
        linkedList.add(new o45.p7());
        linkedList.add(new o45.e2());
        linkedList.add(new o45.la());
        linkedList.add(new o45.r0());
        linkedList.add(new o45.v());
        linkedList.add(new o45.w());
        linkedList.add(new o45.s8());
        linkedList.add(new o45.jc());
        linkedList.add(new o45.k4());
        linkedList.add(new o45.p2());
        linkedList.add(new o45.r1());
        linkedList.add(new o45.sf());
        linkedList.add(new o45.i());
        linkedList.add(new o45.h());
        linkedList.add(new o45.w4());
        return linkedList;
    }
}
