package com.google.android.gms.internal.measurement;

/* loaded from: classes16.dex */
public final class zzew {
    private static final com.google.android.gms.internal.measurement.zzxc zzagc;
    private static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzagd;
    private static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzage;
    private static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzagf;
    private static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzagg;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzagh;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.String> zzagi;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzagj;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzagk;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzagl;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.String> zzagm;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.String> zzagn;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzago;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzagp;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzagq;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzagr;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzags;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzagt;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzagu;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzagv;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzagw;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzagx;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.String> zzagy;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzagz;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzaha;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzahb;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzahc;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzahd;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzahe;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzahf;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzahg;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzahh;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzahi;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzahj;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzahk;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzahl;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzahm;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzahn;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzaho;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzahp;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.String> zzahq;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Long> zzahr;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Integer> zzahs;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Double> zzaht;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzahu;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzahv;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzahw;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzahx;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzahy;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzahz;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzaia;
    private static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzaib;
    public static com.google.android.gms.internal.measurement.zzex<java.lang.Boolean> zzaic;

    static {
        java.lang.String valueOf = java.lang.String.valueOf(android.net.Uri.encode("com.google.android.gms.measurement"));
        zzagc = new com.google.android.gms.internal.measurement.zzxc(android.net.Uri.parse(valueOf.length() != 0 ? "content://com.google.android.gms.phenotype/".concat(valueOf) : new java.lang.String("content://com.google.android.gms.phenotype/")));
        zzagd = com.google.android.gms.internal.measurement.zzex.zzb("measurement.log_third_party_store_events_enabled", false, false);
        zzage = com.google.android.gms.internal.measurement.zzex.zzb("measurement.log_installs_enabled", false, false);
        zzagf = com.google.android.gms.internal.measurement.zzex.zzb("measurement.log_upgrades_enabled", false, false);
        zzagg = com.google.android.gms.internal.measurement.zzex.zzb("measurement.log_androidId_enabled", false, false);
        zzagh = com.google.android.gms.internal.measurement.zzex.zzb("measurement.upload_dsid_enabled", false, false);
        zzagi = com.google.android.gms.internal.measurement.zzex.zzd("measurement.log_tag", "FA", "FA-SVC");
        zzagj = com.google.android.gms.internal.measurement.zzex.zzb("measurement.ad_id_cache_time", com.tencent.tav.decoder.EncoderWriter.HANDLE_FRAME_OPERATE_TIMEOUT, com.tencent.tav.decoder.EncoderWriter.HANDLE_FRAME_OPERATE_TIMEOUT);
        zzagk = com.google.android.gms.internal.measurement.zzex.zzb("measurement.monitoring.sample_period_millis", 86400000L, 86400000L);
        zzagl = com.google.android.gms.internal.measurement.zzex.zzb("measurement.config.cache_time", 86400000L, 3600000L);
        zzagm = com.google.android.gms.internal.measurement.zzex.zzd("measurement.config.url_scheme", "https", "https");
        zzagn = com.google.android.gms.internal.measurement.zzex.zzd("measurement.config.url_authority", "app-measurement.com", "app-measurement.com");
        zzago = com.google.android.gms.internal.measurement.zzex.zzc("measurement.upload.max_bundles", 100, 100);
        zzagp = com.google.android.gms.internal.measurement.zzex.zzc("measurement.upload.max_batch_size", 65536, 65536);
        zzagq = com.google.android.gms.internal.measurement.zzex.zzc("measurement.upload.max_bundle_size", 65536, 65536);
        zzagr = com.google.android.gms.internal.measurement.zzex.zzc("measurement.upload.max_events_per_bundle", 1000, 1000);
        zzags = com.google.android.gms.internal.measurement.zzex.zzc("measurement.upload.max_events_per_day", 100000, 100000);
        zzagt = com.google.android.gms.internal.measurement.zzex.zzc("measurement.upload.max_error_events_per_day", 1000, 1000);
        zzagu = com.google.android.gms.internal.measurement.zzex.zzc("measurement.upload.max_public_events_per_day", 50000, 50000);
        zzagv = com.google.android.gms.internal.measurement.zzex.zzc("measurement.upload.max_conversions_per_day", 500, 500);
        zzagw = com.google.android.gms.internal.measurement.zzex.zzc("measurement.upload.max_realtime_events_per_day", 10, 10);
        zzagx = com.google.android.gms.internal.measurement.zzex.zzc("measurement.store.max_stored_events_per_app", 100000, 100000);
        zzagy = com.google.android.gms.internal.measurement.zzex.zzd("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a");
        zzagz = com.google.android.gms.internal.measurement.zzex.zzb("measurement.upload.backoff_period", 43200000L, 43200000L);
        zzaha = com.google.android.gms.internal.measurement.zzex.zzb("measurement.upload.window_interval", 3600000L, 3600000L);
        zzahb = com.google.android.gms.internal.measurement.zzex.zzb("measurement.upload.interval", 3600000L, 3600000L);
        zzahc = com.google.android.gms.internal.measurement.zzex.zzb("measurement.upload.realtime_upload_interval", com.tencent.tav.decoder.EncoderWriter.HANDLE_FRAME_OPERATE_TIMEOUT, com.tencent.tav.decoder.EncoderWriter.HANDLE_FRAME_OPERATE_TIMEOUT);
        zzahd = com.google.android.gms.internal.measurement.zzex.zzb("measurement.upload.debug_upload_interval", 1000L, 1000L);
        zzahe = com.google.android.gms.internal.measurement.zzex.zzb("measurement.upload.minimum_delay", 500L, 500L);
        zzahf = com.google.android.gms.internal.measurement.zzex.zzb("measurement.alarm_manager.minimum_interval", 60000L, 60000L);
        zzahg = com.google.android.gms.internal.measurement.zzex.zzb("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L);
        zzahh = com.google.android.gms.internal.measurement.zzex.zzb("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L);
        zzahi = com.google.android.gms.internal.measurement.zzex.zzb("measurement.upload.initial_upload_delay_time", 15000L, 15000L);
        zzahj = com.google.android.gms.internal.measurement.zzex.zzb("measurement.upload.retry_time", 1800000L, 1800000L);
        zzahk = com.google.android.gms.internal.measurement.zzex.zzc("measurement.upload.retry_count", 6, 6);
        zzahl = com.google.android.gms.internal.measurement.zzex.zzb("measurement.upload.max_queue_time", 2419200000L, 2419200000L);
        zzahm = com.google.android.gms.internal.measurement.zzex.zzc("measurement.lifetimevalue.max_currency_tracked", 4, 4);
        zzahn = com.google.android.gms.internal.measurement.zzex.zzc("measurement.audience.filter_result_max_count", 200, 200);
        zzaho = com.google.android.gms.internal.measurement.zzex.zzb("measurement.service_client.idle_disconnect_millis", 5000L, 5000L);
        zzahp = com.google.android.gms.internal.measurement.zzex.zzb("measurement.test.boolean_flag", false, false);
        zzahq = com.google.android.gms.internal.measurement.zzex.zzd("measurement.test.string_flag", "---", "---");
        zzahr = com.google.android.gms.internal.measurement.zzex.zzb("measurement.test.long_flag", -1L, -1L);
        zzahs = com.google.android.gms.internal.measurement.zzex.zzc("measurement.test.int_flag", -2, -2);
        zzaht = com.google.android.gms.internal.measurement.zzex.zza("measurement.test.double_flag", -3.0d, -3.0d);
        zzahu = com.google.android.gms.internal.measurement.zzex.zzb("measurement.lifetimevalue.user_engagement_tracking_enabled", false, false);
        zzahv = com.google.android.gms.internal.measurement.zzex.zzb("measurement.audience.complex_param_evaluation", false, false);
        zzahw = com.google.android.gms.internal.measurement.zzex.zzb("measurement.validation.internal_limits_internal_event_params", false, false);
        zzahx = com.google.android.gms.internal.measurement.zzex.zzb("measurement.quality.unsuccessful_update_retry_counter", false, false);
        zzahy = com.google.android.gms.internal.measurement.zzex.zzb("measurement.iid.disable_on_collection_disabled", true, true);
        zzahz = com.google.android.gms.internal.measurement.zzex.zzb("measurement.app_launch.call_only_when_enabled", true, true);
        zzaia = com.google.android.gms.internal.measurement.zzex.zzb("measurement.run_on_worker_inline", true, false);
        zzaib = com.google.android.gms.internal.measurement.zzex.zzb("measurement.audience.dynamic_filters", false, false);
        zzaic = com.google.android.gms.internal.measurement.zzex.zzb("measurement.reset_analytics.persist_time", false, false);
    }
}
