package com.tencent.mm.autogen.layout;

/* loaded from: classes13.dex */
public class BootX2CFactory extends xn5.i {
    public BootX2CFactory() {
        java.lang.System.currentTimeMillis();
        this.f455679a = new java.util.HashMap(24);
        g(com.tencent.mm.R.layout.f489183bl5, new bm.l());
        g(com.tencent.mm.R.layout.csl, new bm.p());
        g(com.tencent.mm.R.layout.crn, new bm.m());
        bm.a aVar = new bm.a();
        java.lang.Integer valueOf = java.lang.Integer.valueOf(com.tencent.mm.R.layout.dba);
        g(com.tencent.mm.R.layout.dba, aVar);
        g(com.tencent.mm.R.layout.bkp, new bm.k());
        g(com.tencent.mm.R.layout.crq, new bm.n());
        bm.i iVar = new bm.i();
        java.lang.Integer valueOf2 = java.lang.Integer.valueOf(com.tencent.mm.R.layout.dbo);
        g(com.tencent.mm.R.layout.dbo, iVar);
        bm.j jVar = new bm.j();
        java.lang.Integer valueOf3 = java.lang.Integer.valueOf(com.tencent.mm.R.layout.dbp);
        g(com.tencent.mm.R.layout.dbp, jVar);
        bm.g gVar = new bm.g();
        java.lang.Integer valueOf4 = java.lang.Integer.valueOf(com.tencent.mm.R.layout.dbj);
        g(com.tencent.mm.R.layout.dbj, gVar);
        g(com.tencent.mm.R.layout.dbc, new bm.c());
        g(com.tencent.mm.R.layout.e1h, new bm.f());
        g(com.tencent.mm.R.layout.ct6, new bm.u());
        g(com.tencent.mm.R.layout.dbb, new bm.b());
        g(com.tencent.mm.R.layout.csr, new bm.r());
        g(com.tencent.mm.R.layout.f489518ct4, new bm.t());
        g(com.tencent.mm.R.layout.ctb, new bm.v());
        g(com.tencent.mm.R.layout.epn, new bm.x());
        g(com.tencent.mm.R.layout.cs7, new bm.o());
        bm.e eVar = new bm.e();
        java.lang.Integer valueOf5 = java.lang.Integer.valueOf(com.tencent.mm.R.layout.dbe);
        g(com.tencent.mm.R.layout.dbe, eVar);
        g(com.tencent.mm.R.layout.csy, new bm.s());
        g(com.tencent.mm.R.layout.e1w, new bm.h());
        bm.d dVar = new bm.d();
        java.lang.Integer valueOf6 = java.lang.Integer.valueOf(com.tencent.mm.R.layout.dbd);
        g(com.tencent.mm.R.layout.dbd, dVar);
        g(com.tencent.mm.R.layout.cul, new bm.w());
        g(com.tencent.mm.R.layout.dif, new bm.q());
        java.util.HashMap hashMap = this.f455679a;
        if (hashMap != null) {
            hashMap.size();
        }
        java.lang.System.currentTimeMillis();
        java.util.HashSet hashSet = new java.util.HashSet();
        hashSet.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.a2l));
        hashSet.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.byv));
        hashSet.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.f489565d01));
        hashSet.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.f489366cb1));
        hashSet.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.c0n));
        hashSet.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.bz_));
        hashSet.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.cyl));
        hashSet.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.c2p));
        java.util.HashMap hashMap2 = this.f455680b;
        hashMap2.put("ContactInfoUI", hashSet);
        java.util.HashSet hashSet2 = new java.util.HashSet();
        hashSet2.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.crn));
        hashSet2.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.crp));
        hashSet2.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.csy));
        hashSet2.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.csl));
        hashSet2.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.cs7));
        hashSet2.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.f489518ct4));
        hashSet2.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.ct6));
        hashMap2.put("SnsTimeLineUI", hashSet2);
        java.util.HashSet hashSet3 = new java.util.HashSet();
        hashSet3.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.bbw));
        hashSet3.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.bbp));
        hashSet3.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.bc_));
        hashSet3.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.f489117bc2));
        hashSet3.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.f487918bk));
        hashMap2.put("FTSDetailUI", hashSet3);
        java.util.HashSet hashSet4 = new java.util.HashSet();
        hashSet4.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.e1w));
        hashSet4.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.e1h));
        hashSet4.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.dbb));
        hashSet4.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.dbc));
        hashSet4.add(valueOf5);
        hashSet4.add(valueOf6);
        hashSet4.add(valueOf4);
        hashSet4.add(valueOf2);
        hashSet4.add(valueOf3);
        hashSet4.add(valueOf);
        hashMap2.put("ChattingFragment", hashSet4);
        java.util.HashSet hashSet5 = new java.util.HashSet();
        hashSet5.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.f489274by5));
        hashSet5.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.bvp));
        hashSet5.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.f487919bl));
        hashSet5.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.f487912be));
        hashSet5.add(java.lang.Integer.valueOf(com.tencent.mm.R.layout.f487913bf));
        hashMap2.put("LauncherUI", hashSet5);
        java.util.HashMap hashMap3 = new java.util.HashMap();
        hashMap3.put(valueOf4, 10);
        hashMap3.put(valueOf, 12);
        hashMap3.put(valueOf2, 10);
        hashMap3.put(valueOf5, 12);
        hashMap3.put(valueOf6, 12);
        hashMap3.put(valueOf3, 12);
        this.f455681c.put("ChattingFragment", hashMap3);
    }
}
