package com.tencent.cloud.huiyan.enums;

/* loaded from: classes14.dex */
public enum AuthState {
    PREPARE,
    AUTH_ACTION,
    START_GET_LIVE_TYPE,
    ON_WS_NEXT_STEP,
    START_CAMERA_PREVIEW,
    ON_FIRST_FOUND_FACE,
    ON_ENTRY_OTHER_ACTION,
    ON_ENTRY_BOT,
    ON_EXIT_BOT,
    ON_MASK_CHANGE,
    ON_DIS_CHANGE_OVER,
    ALL_ACTION_DONE,
    COUNT_DOWN_TIME,
    ON_WS_END_LIVE,
    ON_PUBLIC_WS_END_LIVE,
    AUTH_END,
    ON_START_LOADING_ANIM,
    AUTH_FAIL,
    AUTH_ERROR_DIALOG,
    ON_LOCAL_RETRY,
    START_REFLECT,
    CAMERA_PARAMS_CHANGED,
    CAMERA_PARAMS_STATE_CHANGED,
    CAMERA_RESOLUTION
}
